==== *8.1.2 Base Floating-point Instruction*

[.text-justify]
This chapter will introduce the floating-point instructions in the non privileged subset foundation of the LoongArch architecture. Functional definition of the Basic Floating-point Instruction in the LoongArch Architecture.

[.text-justify]
Comply with *`IEEE 754-2008 standard`*. The basic floating-point instruction cannot be implemented separately from the basic integer instruction. Both the basic integer instruction and the basic floating-point instruction need to be implemented simultaneously. Whether the implementation of basic floating-point instructions includes instructions for manipulating double precision floating-point numbers and doubleword integers is independent of whether the architecture is *`LA32`* or *`LA64`*.

include::8.1.2-Base_Floating-Point_Instructions/8.1.2.1-Floating-Point_Arithmetic_Operation_Instructions.adoc[]

<<<

include::8.1.2-Base_Floating-Point_Instructions/8.1.2.2-Floating-Point_Comparison_Instructions.adoc[]

<<<

include::8.1.2-Base_Floating-Point_Instructions/8.1.2.3-Floating-Point_Conversion_Instructions.adoc[]

<<<

include::8.1.2-Base_Floating-Point_Instructions/8.1.2.4-Floating-Point_Move_Instructions.adoc[]

<<<

include::8.1.2-Base_Floating-Point_Instructions/8.1.2.5-Floating-Point_Branch_Instructions.adoc[]

<<<

include::8.1.2-Base_Floating-Point_Instructions/8.1.2.6-Floating-Point_Common_Memory_Access_Instructions.adoc[]

<<<

include::8.1.2-Base_Floating-Point_Instructions/8.1.2.7-Floating-Point_Bound_Check_Memory_Access_Instructions.adoc[]
