===== *8.1.1.3 Bit-manipulation Instructions*

====== *8.1.1.3.1 `EXT.W.{B/H}`*

*Syntax:*

 opcode    dest,  src1

[options="header"]
[cols="80,10,10"]
|===========================
^.^|opcode
^.^|dest 
^.^|src1

^.^|*`ext.w.b`*, *`ext.w.h`*
^.^|*`$rd`*
^.^|*`$rj`* 
|===========================

*Description :*

*`ext.w.b`* : *`$rd`*[63:0] = *SignExtend*(*`$rj`*[ 7 :0], GRLEN)

*`ext.w.h`* : *`$rd`*[63:0] = *SignExtend*(*`$rj`*[15:0], GRLEN)

*Usage :* 
[source]
----
li.d       $r23, 0x1111111111118111    # $r23 = 0x1111111111118111
ext.w.b    $r25, $r23                  # $r25 = 0x0000000000000011
ext.w.h    $r25, $r23                  # $r25 = 0xffffffffffff8111
----

[NOTE]
=====
For more information, refer to the *`LoongArch instruction manual:2.2.3.1`* .
=====

====== *8.1.1.3.2 `CL{O/Z}.{W/D}`, `CT{O/Z}.{W/D}`*

This section involves four functions, namely CLO, CLZ, CTO, and CTZ.

* The *CLO* function performs the operation that for the data of bit [63/31:0] in the general register rj, the number of continuous bits 1 is measured from bit 63/31 to bit 0, and the result is written into the general register rd.

* The *CLZ* function performs the operation that for the data of bit [63/31:0] in the general register rj, the number of continuous bits 0 is measured from bit 63/31 to bit 0, and the result is written into the general register rd.

* The *CTO* function performs the operation that for the data of bit [63/31:0] in the general register rj, the number of continuous bits 1 is measured from bit 0 to bit 63/31, and the result is written into the general register rd.

* The *CTZ* function performs the operation that for the data of bit [63/31:0] in the general register rj, the number of continuous bits 0 is measured from bit 0 to bit 63/31, and the result is written into the general register rd.

*Syntax:*

 opcode    dest,  src1

[options="header"]
[cols="80,10,10"]
|===========================
^.^|opcode
^.^|dest 
^.^|src1

^.^|*`clo.w`*, *`clo.d`*
^.^|*`$rd`*
^.^|*`$rj`* 

^.^|*`clz.w`*, *`clz.d`*
^.^|*`$rd`*
^.^|*`$rj`* 

^.^|*`cto.w`*, *`cto.d`*
^.^|*`$rd`*
^.^|*`$rj`* 

^.^|*`ctz.w`*, *`ctz.d`*
^.^|*`$rd`*
^.^|*`$rj`* 
|===========================

*Description :*

*`clo.w`* : *`$rd`*[63:0] = *CLO*(*`$rj`*[31:0])

*`clo.d`* : *`$rd`*[63:0] = *CLO*(*`$rj`*[63:0])

*`clz.w`* : *`$rd`*[63:0] = *CLZ*(*`$rj`*[31:0])

*`clz.d`* : *`$rd`*[63:0] = *CLZ*(*`$rj`*[63:0])

*`cto.w`* : *`$rd`*[63:0] = *CTO*(*`$rj`*[31:0])

*`cto.d`* : *`$rd`*[63:0] = *CTO*(*`$rj`*[63:0])

*`ctz.w`* : *`$rd`*[63:0] = *CTZ*(*`$rj`*[31:0])

*`ctz.d`* : *`$rd`*[63:0] = *CTZ*(*`$rj`*[63:0])

*Usage :* 
[source]
----
li.d     $r23, 0xfff00000f00fffff    # $r23 = 0xfff00000f00fffff

clo.w    $r25, $r23                  # $r25 = 4
clo.d    $r25, $r23                  # $r25 = 12
----

* *Explanation:*

** Calculate the number of consecutive bit 1 from bit 31 to bit 0. The operands involved in the calculation are *`0xf00fffff`*, and stop when the first bit 0 occurs. So the result obtained by running the instruction is 4.

** Calculate the number of consecutive bit 1 from bit 63 to bit 0. The operands involved in the calculation are *`0xfff00000f00fffff`*, and stop when the first bit 0 occurs. So the result obtained by running the instruction is 12.

[source]
----
li.d     $r23, 0x000fffff0000ffff    # $r23 = 0x000fffff0000ffff

clz.w    $r25, $r23                  # $r25 = 16
clz.d    $r25, $r23                  # $r25 = 12
----

* *Explanation:*

** Calculate the number of consecutive bit 0 from bit 31 to bit 0. The operands involved in the calculation are *`0x0000ffff`*, and stop when the first bit 0 occurs. So the result obtained by running the instruction is 16.

** Calculate the number of consecutive bit 0 from bit 63 to bit 0. The operands involved in the calculation are *`0x000fffff0000ffff`*, and stop when the first bit 0 occurs. So the result obtained by running the instruction is 12.

[source]
----
li.d     $r23, 0x000fffffffffffff    # $r23 = 0x000fffffffffffff

cto.w    $r25, $r23                  # $r25 = 32
cto.d    $r25, $r23                  # $r25 = 52
----

* *Explanation:*

** Calculate the number of consecutive bit 1 from bit 0 to bit 31. The operands involved in the calculation are *`0xffffffff`*, and stop when the first bit 0 occurs. So the result obtained by running the instruction is 32.

** Calculate the number of consecutive bit 1 from bit 0 to bit 63. The operands involved in the calculation are *`0x000fffffffffffff`*, and stop when the first bit 0 occurs. So the result obtained by running the instruction is 52.

[source]
----
li.d     $r23, 0xfff0000000000000    # $r23 = 0xfff0000000000000

ctz.w    $r25, $r23                  # $r25 = 32
ctz.d    $r25, $r23                  # $r25 = 52
----

* *Explanation:*

** Calculate the number of consecutive bit 0 from bit 0 to bit 31. The operands involved in the calculation are *`0x00000000`*, and stop when the first bit 0 occurs. So the result obtained by running the instruction is 32.

** Calculate the number of consecutive bit 0 from bit 0 to bit 63. The operands involved in the calculation are *`0xfff0000000000000`*, and stop when the first bit 0 occurs. So the result obtained by running the instruction is 52.

[NOTE]
=====
For more information, refer to the *`LoongArch instruction manual:2.2.3.2`* .
=====

====== *8.1.1.3.3 `BYTEPICK.{W/D}`*

*Syntax:*

 opcode    dest,  src1,  src2,  ShiftAmount

[options="header"]
[cols="50,10,10,10,20"]
|===========================
^.^|opcode
^.^|dest 
^.^|src1
^.^|src2
^.^|ShiftAmount

^.^|*`bytepick.w`*
^.^|*`$rd`*
^.^|*`$rj`* 
^.^|*`$rk`*
^.^|{*`0`,`1`,`2`,`3`*}

^.^|*`bytepick.d`*
^.^|*`$rd`*
^.^|*`$rj`* 
^.^|*`$rk`*
^.^|{*`0`,`1`,`2`,`3`,`4`,`5`,`6`,`7`*}
|===========================

*Description :*

*`bytepick.w`* : *`$rd`*[63:0] = *SignExtend*( { *`$rk`*[8×(4-*`SA`*)-1:0], *`$rj`*[31:8×(4-*`SA`*)] }[31:0], GRLEN)

*`bytepick.d`* : *`$rd`*[63:0] = { *`$rk`*[8×(8-*`ShiftAmount`*)-1:0], *`$rj`*[63:8×(8-*`ShiftAmount`*)] }

*Usage :* 

[source]
----
li.d        $r23, 0x0000000001230000    # $r23 = 0x0000000001230000
li.d        $r24, 0x0000000000004567    # $r24 = 0x0000000000004567
bytepick.w  $r25, $r23, $r24, sa2       # $r25 = 0x0000000045670123


li.d        $r23, 0x0123456700000000    # $r23 = 0x0123456700000000
li.d        $r24, 0x0000000089abcdef    # $r24 = 0x0000000089abcdef 
bytepick.d  $r25, $r23, $r24, sa3       # $r25 = 0x89abcdef01234567
----

* *Explanation:*

** When *`ShiftAmount`* = 2:

*** *`bytepick.w`* : *`$r25`*[63:0] = *SignExtend*( {*`$r24`*[15:0], *`$r23`*[31:16]}[31:0], GRLEN)

*** *`$r25`* = *`0x0000000045670123`*

** When *`ShiftAmount`* = 4:

*** *`bytepick.w`* : *`$r25`*[63:0] = {*`$r24`*[31:0], *`$r23`*[63:32]}

*** *`$r25`* = *`0x89abcdef01234567`*

[NOTE]
=====
For more information, refer to the *`LoongArch instruction manual:2.2.3.3`* .
=====

====== *8.1.1.3.4 `REVB.{2H/4H/2W/D}`*

*Syntax:*

 opcode    dest,  src1

[options="header"]
[cols="80,10,10"]
|===========================
^.^|opcode
^.^|dest 
^.^|src1

^.^|*`revb.2h`*, *`revb.4h`*, *`revb.2w`*, *`revb.d`*
^.^|*`$rd`*
^.^|*`$rj`* 
|===========================

*Description :*

*`revb.2h`* : *`$rd`*[63:0] = *SignExtend*( *`$rj`*{[23:16], [31:24], [ 7 : 0 ], [15: 8 ]}, GRLEN)

*`revb.4h`* : *`$rd`*[63:0] = *`$rj`*{[55:48], [63:56], [39:32], [47:40], [23:16], [31:24], [ 7 : 0 ], [15: 8 ]}

*`revb.2w`* : *`$rd`*[63:0] = *`$rj`*{[39:32], [47:40], [55:48], [63:56], [ 7 : 0 ], [15: 8 ], [23:16], [31:24]}

*`revb.d`* : *`$rd`*[63:0] = *`$rj`*{[ 7 : 0 ], [15: 8 ], [23:16], [31:24], [39:32], [47:40], [55:48], [63:56]}

*Usage :* 
[source]
----
li.d       $r23, 0xfedcba9876543210    # $r23 = 0xfedcba9876543210
revb.2h    $r25, $r23                  # $r25 = 0x0000000054761032  
revb.4h    $r25, $r23                  # $r25 = 0xdcfe98ba54761032 
revb.2w    $r25, $r23                  # $r25 = 0x98badcfe10325476 
revb.d     $r25, $r23                  # $r25 = 0x1032547698badcfe
----

* *Explanation:*

** Function description of the *`revb`* series instructions: Reverse the byte data within a specified range, with different suffixes determining different ranges. 

** *`revb.2h`* represents dividing the data into two halfwords, and reversing the bytes in each of the two halfwords. 

*** When using the *`revb.h`* instruction to process *`0xfedcba9876543210`*, only data between bit 31 and bit 0 will be processed. *`0x76543210`* will be divided into two halfwords, namely *`0x7654`* and *`0x3210`*, and the bytes in the two will be arranged in reverse to obtain *`0x5476`* and *`0x1032`*. The final result is *`0x0000000054761032`*.

*** *`0xfedcba98 7654 3210`* -> *`revb`*(*`7654`, `3210`*) -> *`0x0000000054761032`*

** *`revb.4h`* means dividing the data into four halfwords and arranging the bytes in reverse order in each of the two halfwords. 

*** *`0xfedc ba98 7654 3210`* -> *`revb`*(*`fedc`, `ba98`, `7654`, `3210`*) -> *`0xdcfe98ba54761032`*

** *`revb.2w`* means dividing the data into two words and arranging the bytes in reverse in each word. 

*** *`0xfedcba98 76543210`* -> *`revb`*(*`fedcba98`, `76543210`*) -> *`0x98badcfe10325476`*

** *`revb.d`* represents the reverse arrangement of bytes in the entire doubleword data.

*** *`0xfedcba9876543210`* -> *`revb`*(*`fedcba9876543210`*) -> *`0x1032547698badcfe`*

[NOTE]
=====
For more information, refer to the *`LoongArch instruction manual:2.2.3.4`* .
=====

====== *8.1.1.3.5 `REVH.{2W/D}`*

*Syntax:*

 opcode    dest,  src1

[options="header"]
[cols="80,10,10"]
|===========================
^.^|opcode
^.^|dest 
^.^|src1

^.^|*`revh.2w`*, *`revh.d`*
^.^|*`$rd`*
^.^|*`$rj`* 
|===========================

*Description :*

*`revh.2w`* : *`$rd`*[63:0] = *`$rj`*{[47:32], [63:48], [15: 0 ], [31:16]}

*`revh.d`* : *`$rd`*[63:0] = *`$rj`*{[15: 0 ], [31:16], [47:32], [63:48]}

*Usage :* 
[source]
----
li.d       $r23, 0xfedcba9876543210    # $r23 = 0xfedcba9876543210
revh.2w    $r25, $r23                  # $r25 = 0xba98fedc32107654 
revh.d     $r25, $r23                  # $r25 = 0x32107654ba98fedc
----

[NOTE]
=====
For more information, refer to the *`LoongArch instruction manual:2.2.3.5`* .
=====

====== *8.1.1.3.6 `BITREV.{4B/8B}`*

The bitrev `*$rj*`[*`a`* : *`b`*] performs the operation that the [*`a`* : *`b`*] bit in general register rj is arranged in reverse order.

*Syntax:*

 opcode    dest,  src1

[options="header"]
[cols="80,10,10"]
|===========================
^.^|opcode
^.^|dest 
^.^|src1

^.^|*`bitrev.4b`*, *`bitrev.8b`*
^.^|*`$rd`*
^.^|*`$rj`* 
|===========================

*Description :*

*`bitrev.4b`* : *`$rd`*[63:0] = *SignExtend*( *`$rj`*{[24:31], [16:23], [ 8 :16], [ 0 : 7 ]}, GRLEN)

*`bitrev.8b`* : *`$rd`*[63:0] = *`$rj`*{[56:63], [48:55], [40:47], [32:39], [24:31], [16:23], [ 8 :16], [ 0 : 7 ]}

*Usage :* 
[source]
----
li.d         $r23, 0xfedcba9876543210    # $r23 = 0xfedcba9876543210
bitrev.4b    $r25, $r23                  # $r25 = 0x000000006e2a4c08 
bitrev.8b    $r25, $r23                  # $r25 = 0x7f3b5d196e2a4c08
----

* *Explanation:*

** *`bitrev.4b`*

*** Divide bit 31 to bit 0 into 4 bytes to perform a bitwise reverse order operation.

*** *`0x10`* -> *`0b00010000`* -> *bitrev*(*`0b00010000`*) -> *`0b00001000`* -> *`0x08`*

*** *`0x32`* -> *`0b00110010`* -> *bitrev*(*`0b00110010`*) -> *`0b01001100`* -> *`0x4c`*

*** *`0x54`* -> *`0b01010100`* -> *bitrev*(*`0b01010100`*) -> *`0b00101010`* -> *`0x2a`*

*** *`0x76`* -> *`0b01110110`* -> *bitrev*(*`0b01110110`*) -> *`0b01101110`* -> *`0x6e`*

*** *`0xfedcba9876543210`* -> *`0x000000006e2a4c08`*

** *`bitrev.8b`*

*** Divide bit 63 to bit 0 into 8 bytes to perform a bitwise reverse order operation.

*** *`0x10`* -> *`0b00010000`* -> *bitrev*(*`0b00010000`*) -> *`0b00001000`* -> *`0x08`*

*** *`0x32`* -> *`0b00110010`* -> *bitrev*(*`0b00110010`*) -> *`0b01001100`* -> *`0x4c`*

*** *`0x54`* -> *`0b01010100`* -> *bitrev*(*`0b01010100`*) -> *`0b00101010`* -> *`0x2a`*

*** *`0x76`* -> *`0b01110110`* -> *bitrev*(*`0b01110110`*) -> *`0b01101110`* -> *`0x6e`*

*** *`0x98`* -> *`0b10011000`* -> *bitrev*(*`0b10011000`*) -> *`0b00011001`* -> *`0x19`*

*** *`0xba`* -> *`0b10111010`* -> *bitrev*(*`0b10111010`*) -> *`0b01011101`* -> *`0x5d`*

*** *`0xdc`* -> *`0b11011100`* -> *bitrev*(*`0b11011100`*) -> *`0b00111011`* -> *`0x3b`*

*** *`0xfe`* -> *`0b11111110`* -> *bitrev*(*`0b11111110`*) -> *`0b01111111`* -> *`0x7f`*

*** *`0xfedcba9876543210`* -> *`0x7f3b5d196e2a4c08`*

[NOTE]
=====
For more information, refer to the *`LoongArch instruction manual:2.2.3.6`* .
=====

====== *8.1.1.3.7 `BITREV.{W/D}`*

The bitrev `*$rj*`[*`a`* : *`b`*] performs the operation that the [*`a`* : *`b`*] bit in general register rj is arranged in reverse order.

*Syntax:*

 opcode    dest,  src1

[options="header"]
[cols="80,10,10"]
|===========================
^.^|opcode
^.^|dest 
^.^|src1

^.^|*`bitrev.w`*, *`bitrev.d`*
^.^|*`$rd`*
^.^|*`$rj`* 
|===========================

*Description :*

*`bitrev.w`* : *`$rd`*[63:0] = *SignExtend*(*`$rj`*[0:31], GRLEN)

*`bitrev.d`* : *`$rd`*[63:0] = *`$rj`*[0:63]

*Usage :* 
[source]
----
li.d        $r23, 0xfedcba9876543210    # $r23 = 0xfedcba9876543210
bitrev.w    $r25, $r23                  # $r25 = 0x00000000084c2a6e
bitrev.d    $r25, $r23                  # $r25 = 0x084c2a6e195d3b7f
----

* *Explanation:*

** *`bitrev.w`*

*** *`0xfedcba9876543210`*

*** *`0b 0111 0110 0101 0100 0011 0010 0001 0000`*

*** *bitrev*(*`0b01110110010101000011001000010000`*)

*** *`0b 0000 1000 0100 1100 0010 1010 0110 1110`*

*** *`0x00000000084c2a6e`*

** *`bitrev.d`*

*** *`0xfedcba9876543210`*

*** *`0b 1111 1110 1101 1100 1011 1010 1001 1000 0111 0110 0101 0100 0011 0010 0001 0000`*

*** *bitrev*(*`0b1111111011011100101110101001100001110110010101000011001000010000`*)

*** *`0b 0000 1000 0100 1100 0010 1010 0110 1110 0001 1001 0101 1101 0011 1011 0111 1111`*

*** *`0x084c2a6e195d3b7f`*

[NOTE]
=====
For more information, refer to the *`LoongArch instruction manual:2.2.3.7`* .
=====

====== *8.1.1.3.8 `BSTRINS.{W/D}`*

*Syntax:*

 opcode    dest,  src1,  src2,  src3

[options="header"]
[cols="60,10,10,10,10"]
|===========================
^.^|opcode
^.^|dest 
^.^|src1
^.^|src2
^.^|src3

^.^|*`bstrins.w`*
^.^|*`$rd`*
^.^|*`$rj`* 
^.^|*`msbw`* 
^.^|*`lsbw`* 

^.^|*`bstrins.d`*
^.^|*`$rd`*
^.^|*`$rj`* 
^.^|*`msbd`* 
^.^|*`lsbd`* 
|===========================

*Description :*

*`bstrins.w`* : *`$rd`*[63:0] = *SignExtend*({*`$rd`*[31: *`msbw`*+1], *`$rj`*[*`msbw`*-*`lsbw`*:0], *`$rd`*[*`lsbw`*-1: 0]}, GRLEN)

** *`msbw`*, *`lsbw`*  : Unsigned value range(*`integer`*) : *31* > *`msbw`* > *`lsbw`* > *0*

*`bstrins.d`* : *`$rd`*[63:0] = {*`$rd`*[63: *`msbd`*+1], *`$rj`*[*`msbd`*-*`lsbd`*:0], *`$rd`*[*`lsbd`*-1: 0]}

** *`msbd`*, *`lsbd`*  : Unsigned value range(*`integer`*) : *63* > *`msbd`* > *`lsbd`* > *0*

*Usage :* 
[source]
----
li.d       $r23, 0x0123456789abcdef    # $r23 = 0x0123456789abcdef
li.d       $r25, 0xfedcba9876543210    # $r25 = 0xfedcba9876543210
bstrins.w  $r25, $r23, 15, 8
bstrins.d  $r25, $r23, 51, 8   
----

* *Explanation:*

** *`bstrins.w`*

*** *`$r25`*[31:16] = *`0x7654`*, *`$r23`*[ 7 : 0 ] = *`0xef`*, *`$r25`*[ 7 : 0 ] = *`0x10`*

*** *`$r25`*[31: 0 ] = *SignExtend*({*`7654`*, *`ef`*, *`10`*}, GRLEN) = *`0x000000007654ef10`*

** *`bstrins.d`*

*** *`$r25`*[63:52] = *`0xfed`*, *`$r23`*[43: 0 ] = *`0x56789abcdef`*, *`$r25`*[ 7 : 0 ] = *`0x10`*

*** *`$r25`*[31: 0 ] = {*`fed`*, *`56789abcdef`*, *`10`*} = *`0xfed56789abcdef10`*

[NOTE]
=====
For more information, refer to the *`LoongArch instruction manual:2.2.3.8`* .
=====

====== *8.1.1.3.9 `BSTRPICK.{W/D}`*

*Syntax:*

 opcode    dest,  src1,  src2,  src3

[options="header"]
[cols="60,10,10,10,10"]
|===========================
^.^|opcode
^.^|dest 
^.^|src1
^.^|src2
^.^|src3

^.^|*`bstrpick.w`*
^.^|*`$rd`*
^.^|*`$rj`* 
^.^|*`msbw`* 
^.^|*`lsbw`* 

^.^|*`bstrpick.d`*
^.^|*`$rd`*
^.^|*`$rj`* 
^.^|*`msbd`* 
^.^|*`lsbd`* 
|===========================

*Description :*

*`bstrpick.w`* : *`$rd`*[63:0] = *SignExtend* ( *ZeroExtend*(*`$rj`*[*`msbw`* : *`lsbw`*], 32), GRLEN)

** *`msbw`*, *`lsbw`*  : Unsigned value range(*`integer`*) : *31* > *`msbw`* > *`lsbw`* > *0*

*`bstrpick.d`* : *`$rd`*[63:0] = *ZeroExtend*(*`$rj`*[*`msbd`* : *`lsbd`*], 64)

** *`msbd`*, *`lsbd`*  : Unsigned value range(*`integer`*) : *63* > *`msbd`* > *`lsbd`* > *0*

*Usage :* 
[source]
----
li.d        $r23, 0x0123456789abcdef    # $r23 = 0x0123456789abcdef
li.d        $r25, 0x0000000000000000    # $r25 = 0x0000000000000000

bstrpick.w  $r25, $r23, 15, 8           # $r25 = 0x00000000000000cd

bstrpick.d  $r25, $r23, 51, 8           # $r25 = 0x000003456789abcd
----

* *Explanation:*

** *`bstrpick.w`*

*** *`$r23`*[15: 8 ] = *`0xcd`*, 

*** *`$r25`*[63:0] = *SignExtend* ( *ZeroExtend*( *`0xcd`*, 32 ), GRLEN) = *`0x00000000000000cd`*

** *`bstrpick.d`*

*** *`$r23`*[51: 8 ] = *`0x3456789abcd`*, 

*** *`$r25`*[63:0] = *ZeroExtend* ( *`0x3456789abcd`*, 64 ) = *`0x000003456789abcd`*

[NOTE]
=====
For more information, refer to the *`LoongArch instruction manual:2.2.3.9`* .
=====

====== *8.1.1.3.10 `MASKEQZ`, `MASKNEZ`*

*Syntax:*

 opcode    dest,  src1,  src2

[options="header"]
[cols="70,10,10,10"]
|===========================
^.^|opcode
^.^|dest 
^.^|src1
^.^|src2

^.^|*`maskeqz`*, *`masknez`*
^.^|*`$rd`*
^.^|*`$rj`* 
^.^|*`$rk`* 
|===========================

*Description :*

*`maskeqz`* : *`$rd`* = (*`$rk`* == 0) ? 0 : *`$rj`*

*`masknez`* : *`$rd`* = (*`$rk`* ! = 0) ? 0 : *`$rj`*

*Usage :* 
[source]
----
maskeqz  $r25, $r23, $r24
masknez  $r25, $r23, $r24 
----

[NOTE]
=====
For more information, refer to the *`LoongArch instruction manual:2.2.3.10`* .
=====
