===== *8.1.1.6 Bound Check Memory Access Instructions*

====== *8.1.1.6.1 `LD{GT/LE}.{B/H/W/D}`*

*Syntax:*

 opcode    dest,  src1,  src2

[options="header"]
[cols="70,10,10,10"]
|===========================
^.^|opcode
^.^|dest
^.^|src1 
^.^|src2

^.^|*`ldgt.b`*, *`ldgt.h`*, *`ldgt.w`*, *`ldgt.d`*, *`ldle.b`*, *`ldle.h`*, *`ldle.w`*, *`ldle.d`*
^.^|*`$rd`*
^.^|*`$rj`* 
^.^|*`$rk`* 
|===========================

*Description :*

*`ldgt.{b/h/w/d}`* :

** *if*(*`$rj`* *>* *`$rk`*)*`$rd`* = *SignExtend*( *MemoryLoad* (*`$rj`*, *`byte`*/*`halfword`*/*`word`*/*`doubleword`*), GRLEN)
** *else* : *RaiseException*(BCE)

*`ldle.{b/h/w/d}`* :

** *if*(*`$rj`* *<=* *`$rk`*)*`$rd`* = *SignExtend*( *MemoryLoad* (*`$rj`*, *`byte`*/*`halfword`*/*`word`*/*`doubleword`*), GRLEN)
** *else* : *RaiseException*(BCE)

*Usage :* 
[source]
----
ldgt.b     $r23,  $r24,  $r25    # $r23 = 0x0000000000000010
ldgt.h     $r23,  $r24,  $r25    # $r23 = 0x0000000000003210
ldgt.w     $r23,  $r24,  $r25    # $r23 = 0x0000000076543210
ldgt.d     $r23,  $r24,  $r25    # $r23 = 0xfedcba9876543210
ldle.b     $r23,  $r24,  $r25    # $r23 = 0x0000000000000010
ldle.h     $r23,  $r24,  $r25    # $r23 = 0x0000000000003210
ldle.w     $r23,  $r24,  $r25    # $r23 = 0x0000000076543210
ldle.d     $r23,  $r24,  $r25    # $r23 = 0xfedcba9876543210
----

[NOTE]
=====
For more information, refer to the *`LoongArch instruction manual:2.2.6.1`* .
=====

====== *8.1.1.6.2 `ST{GT/LE}.{B/H/W/D}`*

*Syntax:*

 opcode    dest,  src1,  src2

[options="header"]
[cols="70,10,10,10"]
|===========================
^.^|opcode
^.^|src1
^.^|src2 
^.^|src3

^.^|*`stgt.b`*, *`stgt.h`*, *`stgt.w`*, *`stgt.d`*, *`stle.b`*, *`stle.h`*, *`stle.w`*, *`stle.d`*
^.^|*`$rd`*
^.^|*`$rj`* 
^.^|*`$rk`* 
|===========================

*Description :*

*`stgt.{b/h/w/d}`* :

* *if*(*`$rj`* > *`$rk`*)
** *MemoryStore*(*`$rd`*[ 7 :0],*`$rj`*,*`byte`*)/
** *MemoryStore*(*`$rd`*[15:0],*`$rj`*,*`halfword`*)/
** *MemoryStore*(*`$rd`*[31:0],*`$rj`*,*`word`*)/
** *MemoryStore*(*`$rd`*[63:0],*`$rj`*,*`doubleword`*)
* *else* :
** *RaiseException*(BCE)

*`stle.{b/h/w/d}`* :

* *if*(*`$rj`* < = *`$rk`*)
** *MemoryStore*(*`$rd`*[ 7 :0],*`$rj`*,*`byte`*)/
** *MemoryStore*(*`$rd`*[15:0],*`$rj`*,*`halfword`*)/
** *MemoryStore*(*`$rd`*[31:0],*`$rj`*,*`word`*)/
** *MemoryStore*(*`$rd`*[63:0],*`$rj`*,*`doubleword`*)
* *else* :
** *RaiseException*(BCE)

*Usage :* 
[source]
----
stgt.b     $r23,  $r24,  $r25    # memory[$r24] = 0x0000000000000010
stgt.h     $r23,  $r24,  $r25    # memory[$r24] = 0x0000000000003210
stgt.w     $r23,  $r24,  $r25    # memory[$r24] = 0x0000000076543210
stgt.d     $r23,  $r24,  $r25    # memory[$r24] = 0xfedcba9876543210
stle.b     $r23,  $r24,  $r25    # memory[$r24] = 0x0000000000000010
stle.h     $r23,  $r24,  $r25    # memory[$r24] = 0x0000000000003210
stle.w     $r23,  $r24,  $r25    # memory[$r24] = 0x0000000076543210
stle.d     $r23,  $r24,  $r25    # memory[$r24] = 0xfedcba9876543210
----

[NOTE]
=====
For more information, refer to the *`LoongArch instruction manual:2.2.6.1`* .
=====
