===== *8.1.1.5 Common Memory Access Instructions*

[grid=none]
[frame=none]
[cols="50,50"]
|===========================
<.^|*value* = `*MemoryLoad*` ( *address*, *size* )
<.^|`*MemoryStore*` ( *value*, *address*, *size* )
|===========================

====== *8.1.1.5.1 `LD.{B[U]/H[U]/W[U]/D}`*

*Syntax:*

 opcode    dest,  src1,  src2

[options="header"]
[cols="70,10,10,10"]
|===========================
^.^|opcode
^.^|dest
^.^|src1 
^.^|src2

^.^|*`ld.b`*, *`ld.h`*, *`ld.w`*, *`ld.bu`*, *`ld.hu`*, *`ld.wu`*, *`ld.d`*
^.^|*`$rd`*
^.^|*`$rj`* 
^.^|*`si12`* 
|===========================

*Description :*

[grid=none]
[frame=none]
[cols="65,20,915"]
|===========================
<.^|*`ld.b`*
^.^|*:*
<.^|*`$rd`*[63:0] = `*Sign*`*Extend* (`*MemoryLoad*` (*`$rj`* `*+*` `*Sign*`*Extend* (*`si12`*, GRLEN), [ 7 :0]), GRLEN)

<.^|*`ld.h`*
^.^|*:*
<.^|*`$rd`*[63:0] = `*Sign*`*Extend* (`*MemoryLoad*` (*`$rj`* `*+*` `*Sign*`*Extend* (*`si12`*, GRLEN), [15:0]), GRLEN)

<.^|*`ld.w`*
^.^|*:*
<.^|*`$rd`*[63:0] = `*Sign*`*Extend* (`*MemoryLoad*` (*`$rj`* `*+*` `*Sign*`*Extend* (*`si12`*, GRLEN), [31:0]), GRLEN)

<.^|*`ld.bu`*
^.^|*:*
<.^|*`$rd`*[63:0] = `*Zero*`*Extend* (`*MemoryLoad*` (*`$rj`* `*+*` `*Sign*`*Extend* (*`si12`*, GRLEN), [ 7 :0]), GRLEN)

<.^|*`ld.hu`*
^.^|*:*
<.^|*`$rd`*[63:0] = `*Zero*`*Extend* (`*MemoryLoad*` (*`$rj`* `*+*` `*Sign*`*Extend* (*`si12`*, GRLEN), [15:0]), GRLEN)

<.^|*`ld.wu`*
^.^|*:*
<.^|*`$rd`*[63:0] = `*Zero*`*Extend* (`*MemoryLoad*` (*`$rj`* `*+*` `*Sign*`*Extend* (*`si12`*, GRLEN), [31:0]), GRLEN)

<.^|*`ld.d`*
^.^|*:*
<.^|*`$rd`*[63:0] = `*MemoryLoad*` (*`$rj`* `*+*` `*Sign*`*Extend* (*`si12`*, GRLEN), [63:0])
|===========================

* *`si12`* : 12-bit immediate, signed value range(*`integer`*) : [*`-2048`, `2047`*] or [*`-0x800`, `0x7ff`*]

*Usage :* 

[source]
----
                           # memory[$r22 - 40] = 0x0123456789abcdef
ld.b    $r23, $r22, -40    # $r23 = 0xffffffffffffffef
ld.bu   $r23, $r22, -40    # $r23 = 0x00000000000000ef
ld.h    $r23, $r22, -40    # $r23 = 0xffffffffffffcdef
ld.hu   $r23, $r22, -40    # $r23 = 0x000000000000cdef
ld.w    $r23, $r22, -40    # $r23 = 0xffffffff89abcdef
ld.wu   $r23, $r22, -40    # $r23 = 0x0000000089abcdef
ld.d    $r23, $r22, -40    # $r23 = 0x0123456789abcdef
----

[NOTE]
=====
For more information, refer to the *`LoongArch Architecture manual:2.2.5.1`* .
=====

====== *8.1.1.5.2 `ST.{B/H/W/D}`*

*Syntax:*

 opcode    src1,  src2,  src3

[options="header"]
[cols="70,10,10,10"]
|===========================
^.^|opcode
^.^|src1
^.^|src2 
^.^|src3

^.^|*`st.b`*, *`st.h`*, *`st.w`*, *`st.d`*
^.^|*`$rd`*
^.^|*`$rj`* 
^.^|*`si12`* 
|===========================

*Description :*

[grid=none]
[frame=none]
[cols="55,20,925"]
|===========================
<.^|*`st.b`*
^.^|*:*
<.^|`*MemoryStore*` ( *`$rd`*[ 7 :0], ( *`$rj`* `*+*` `*Sign*`*Extend* (*`si12`*, GRLEN) ), [ 7 :0] )

<.^|*`st.h`*
^.^|*:*
<.^|`*MemoryStore*` ( *`$rd`*[15:0], ( *`$rj`* `*+*` `*Sign*`*Extend* (*`si12`*, GRLEN) ), [15:0] )

<.^|*`st.w`*
^.^|*:*
<.^|`*MemoryStore*` ( *`$rd`*[31:0], ( *`$rj`* `*+*` `*Sign*`*Extend* (*`si12`*, GRLEN) ), [31:0] )

<.^|*`st.d`*
^.^|*:*
<.^|`*MemoryStore*` ( *`$rd`*[63:0], ( *`$rj`* `*+*` `*Sign*`*Extend* (*`si12`*, GRLEN) ), [63:0] )
|===========================

* *`si12`* : 12-bit immediate, signed value range(*`integer`*) : [*`-2048`, `2047`*] or [*`-0x800`, `0x7ff`*]

*Usage :* 

[source]
----
li.w $r23, 0xfedcba9876543210   # $r23 = 0xfedcba9876543210 

st.b $r23, $r22, -24            # memory[$r22 - 24] = 0x0000000000000010
st.h $r23, $r22, -24            # memory[$r22 - 24] = 0x0000000000003210
st.w $r23, $r22, -24            # memory[$r22 - 24] = 0x0000000076543210
st.d $r23, $r22, -24            # memory[$r22 - 24] = 0xfedcba9876543210
----

[NOTE]
=====
For more information, refer to the *`LoongArch Architecture manual:2.2.5.1`* .
=====

====== *8.1.1.5.3 `LDX.{B[U]/H[U]/W[U]/D}`*

*Syntax:*

 opcode    dest,  src1,  src2

[options="header"]
[cols="70,10,10,10"]
|===========================
^.^|opcode
^.^|dest
^.^|src1 
^.^|src2

^.^|*`ldx.b`*, *`ldx.h`*, *`ldx.w`*, *`ldx.bu`*, *`ldx.hu`*, *`ldx.wu`*, *`ldx.d`*
^.^|*`$rd`*
^.^|*`$rj`* 
^.^|*`$rk`* 
|===========================

*Description :*

[grid=none]
[frame=none]
[cols="75,20,905"]
|===========================
<.^|*`ldx.b`*
^.^|*:*
<.^|*`$rd`*[63:0] = `*Sign*`*Extend* (`*MemoryLoad*` ( *`$rj`* `*+*` *`$rk`*, [ 7 :0]), GRLEN)

<.^|*`ldx.h`*
^.^|*:*
<.^|*`$rd`*[63:0] = `*Sign*`*Extend* (`*MemoryLoad*` ( *`$rj`* `*+*` *`$rk`*, [15:0]), GRLEN)

<.^|*`ldx.w`*
^.^|*:*
<.^|*`$rd`*[63:0] = `*Sign*`*Extend* (`*MemoryLoad*` ( *`$rj`* `*+*` *`$rk`*, [31:0]), GRLEN)

<.^|*`ldx.bu`*
^.^|*:*
<.^|*`$rd`*[63:0] = `*Zero*`*Extend* (`*MemoryLoad*` ( *`$rj`* `*+*` *`$rk`*, [ 7 :0]), GRLEN)

<.^|*`ldx.hu`*
^.^|*:*
<.^|*`$rd`*[63:0] = `*Zero*`*Extend* (`*MemoryLoad*` ( *`$rj`* `*+*` *`$rk`*, [15:0]), GRLEN)

<.^|*`ldx.wu`*
^.^|*:*
<.^|*`$rd`*[63:0] = `*Zero*`*Extend* (`*MemoryLoad*` ( *`$rj`* `*+*` *`$rk`*, [31:0]), GRLEN)

<.^|*`ldx.d`*
^.^|*:*
<.^|*`$rd`*[63:0] = `*MemoryLoad*` ( *`$rj`* `*+*` *`$rk`*, [63:0])
|===========================

*Usage :*

[source]
----
li.w    $r24, -40           # $r24 = -40

                            # memory[$r22 - $r24] = 0x0123456789abcdef
ldx.b   $r23, $r22, $r24    # $r23 = 0xffffffffffffffef
----

[source]
----
ldx.bu  $r23, $r22, $r24    # $r23 = 0x00000000000000ef
ldx.h   $r23, $r22, $r24    # $r23 = 0xffffffffffffcdef
ldx.hu  $r23, $r22, $r24    # $r23 = 0x000000000000cdef
ldx.w   $r23, $r22, $r24    # $r23 = 0xffffffff89abcdef
ldx.wu  $r23, $r22, $r24    # $r23 = 0x0000000089abcdef
ldx.d   $r23, $r22, $r24    # $r23 = 0x0123456789abcdef
----

[NOTE]
=====
For more information, refer to the *`LoongArch Architecture manual:2.2.5.2`* .
=====

====== *8.1.1.5.4 `STX.{B/H/W/D}`*

*Syntax:*

 opcode    src1,  src2,  src3

[options="header"]
[cols="70,10,10,10"]
|===========================

^.^|opcode
^.^|src1
^.^|src2 
^.^|src3

^.^|*`stx.b`*, *`stx.h`*, *`stx.w`*, *`stx.d`*
^.^|*`$rd`*
^.^|*`$rj`* 
^.^|*`$rk`* 

|===========================

*Description :*

[grid=none]
[frame=none]
[cols="65,20,925"]
|===========================
<.^|*`stx.b`*
^.^|*:*
<.^|`*MemoryStore*` (*`$rd`*[ 7 :0], (*`$rj`* `*+*` *`$rk`*), [ 7 :0])

<.^|*`stx.h`*
^.^|*:*
<.^|`*MemoryStore*` (*`$rd`*[15:0], (*`$rj`* `*+*` *`$rk`*), [15:0])

<.^|*`stx.w`*
^.^|*:*
<.^|`*MemoryStore*` (*`$rd`*[31:0], (*`$rj`* `*+*` *`$rk`*), [31:0])

<.^|*`stx.d`*
^.^|*:*
<.^|`*MemoryStore*` (*`$rd`*[63:0], (*`$rj`* `*+*` *`$rk`*), [63:0])
|===========================

*Usage :* 

[source]
----
li.w   $r24, -40                  # $r24 = -40
li.w   $r23, 0xfedcba9876543210   # $r23 = 0xfedcba9876543210  

stx.b  $r23, $r22, $r24           # memory[$r22 - $r24] = 0x0000000000000010
stx.h  $r23, $r22, $r24           # memory[$r22 - $r24] = 0x0000000000003210
stx.w  $r23, $r22, $r24           # memory[$r22 - $r24] = 0x0000000076543210
stx.d  $r23, $r22, $r24           # memory[$r22 - $r24] = 0xfedcba9876543210
----

[NOTE]
=====
For more information, refer to the *`LoongArch Architecture manual:2.2.5.2`* .
=====

====== *8.1.1.5.5 `LDPTR.{W/D}`*

*Syntax:*

 opcode    dest,  src1,  src2

[options="header"]
[cols="70,10,10,10"]
|===========================
^.^|opcode
^.^|dest
^.^|src1 
^.^|src2

^.^|*`ldptr.w`*, *`ldptr.d`*
^.^|*`$rd`*
^.^|*`$rj`* 
^.^|*`si14`* 
|===========================

*Description :*

[grid=none]
[frame=none]
[cols="85,20,895"]
|===========================
<.^|*`ldptr.w`*
^.^|*:*
<.^|*`$rd`*[63:0] = `*Sign*`*Extend* (`*MemoryLoad*` ( *`$rj`* `*+*` `*Sign*`*Extend*(*`si16`*, GRLEN), [31:0]), GRLEN)

<.^|*`ldptr.d`*
^.^|*:*
<.^|*`$rd`*[63:0] = `*MemoryLoad*` ( *`$rj`* `*+*` `*Sign*`*Extend*(*`si16*`, GRLEN), [63:0])
|===========================

* *`si16`* : a 4-bytes aligned 16-bits signed immediate value in range :

** [*`-32768`*, *`32764`*] or [*`-0x8000`*, *`0x7ffc`*]

*Usage :* 

[source]
----
li.d    $r23, 0x0123456789abcdef

st.d    $r23, $r22, -40    # memory[$r22 - 40] = 0x0123456789abcdef
ldptr.w $r23, $r22, -40    # $r23 = 0xffffffff89abcdef
ldptr.d $r23, $r22, -40    # $r23 = 0x0123456789abcdef
----

[NOTE]
=====
For more information, refer to the *`LoongArch Architecture manual:2.2.5.3`* .
=====

====== *8.1.1.5.6 `STPTR.{W/D}`*

*Syntax:*

 opcode    src1,  src2,  src3

[options="header"]
[cols="70,10,10,10"]
|===========================
^.^|opcode
^.^|src1
^.^|src2 
^.^|src3

^.^|*`stptr.w`*, *`stptr.d`*
^.^|*`$rd`*
^.^|*`$rj`* 
^.^|*`si14`* 
|===========================

*Description :*

[grid=none]
[frame=none]
[cols="85,20,895"]
|===========================
<.^|*`ldptr.w`*
^.^|*:*
<.^|`*MemoryStore*` ( *`$rd`*[31:0], *`$rj`* `*+*` `*Sign*`*Extend*({*`si14`*, 2'b0}, GRLEN), [31:0])

<.^|*`ldptr.d`*
^.^|*:*
<.^|`*MemoryStore*` ( *`$rd`*[63:0], *`$rj`* `*+*` `*Sign*`*Extend*({*`si14`*, 2'b0}, GRLEN), [63:0])
|===========================

* *`si16`* : a 4-bytes aligned 16-bits signed immediate value in range :

** [*`-32768`*, *`32764`*] or [*`-0x8000`*, *`0x7ffc`*]

*Usage :* 

[source]
----
li.d    $r23, 0xfedcba9876543210

stptr.w $r23, $r22, -40    # memory[$r22 - 40] = 0x0000000076543210
stptr.d $r23, $r22, -40    # memory[$r22 - 40] = 0xfedcba9876543210
----

[NOTE]
=====
For more information, refer to the *`LoongArch Architecture manual:2.2.5.3`* .
=====

<<<

====== *8.1.1.5.6 `PRELD`, `PRELDX`*

*Syntax:*

 opcode    src1,  src2,  src3

[options="header"]
[cols="70,10,10,10"]
|===========================
^.^|opcode
^.^|src1
^.^|src2 
^.^|src3

^.^|*`preld`*
^.^|*`hint`*
^.^|*`$rj`* 
^.^|*`si12`* 

^.^|*`preldx`*
^.^|*`hint`*
^.^|*`$rj`* 
^.^|*`$rk`* 
|===========================

*Description :*

*`preld`* : 

* The processor uses the hint in the *`PRELD`* instruction to determine the type of operation and which level of *`Cache`* to fill the data from. The *`hint`* has 32 optional values (0 to 31), where 0 represents a load to level 1 *`Cache`*, and 8 represents a store to level 1 *`Cache`*. The remaining *`hint`* values are not defined and are processed for nop instructions when the processor executes.

* *`si12`* : 12-bit immediate, signed value range(*`integer`*) : [*`-2048`, `2047`*] or [*`-0x800`, `0x7ff`*]

*`preldx`* : 

* The *`PRELDX`* instruction continuously prefetches data from memory into the cache according to the configuration parameters. The prefetch operation retrieves a *`block`* (*`block`*) of data, with a length of *`block_size`*, starting from a specified base *`address`* (*`base`*) and with a spacing stride defined by *`block_num`* . The *`base address`* is the sum of the [63:0] bits in the general register *`rj`* and the sign extension [15:0] bits in the general register *`rk`*. The [I16] bits in general register *`rk`* are the address sequence ascending and descending flag bits, where 0 indicates address ascending and 1 indicates address descending. The value of bits [25:20] in general register *`rk`* is *`block_size`*, with a basic unit of *`block_size`* is 16 bytes, so the maximum length of a single *`block`* is 1KB. The value of bits [39:32] in general register *`rk`* is *`block_num`*-*`1`*, so a single instruction can prefetch up to 256 *`blocks`*. The value of bits [59:44] in the block general register *`rk`* is treated as a signed number and defines the stride between adjacent blocks, with a basic unit of 1 byte. The value of bits [39:32] in *`rk`* is *`block.num`*-*`1`*, so a single instruction can prefetch up to 256 blocks. The value of bits [59:44] in general register *`rk`* is regarded as a signed number that defines the stride between adjacent blocks, with a basic unit of 1 byte.

* The *`hint`* in the *`PRELDX`* instruction indicates the type of prefetch and the level of *`Cache`* into which the fetched data is to be filled. The *`hint`* has 32 selectable values from 0 to 31. Currently, *`hint`*=*`0`* is defined as a load prefetch to level 1 data *`Cache`*, *`hint`*=*`2`* is defined as a load prefetch to level 3 *`Cache`*, *`hint`*=*`8`* is defined as a store prefetch to level 1 data *`Cache`*. The meanings of the remaining *`hint`* values are not yet defined and the processor executes it as *`NOP`* instruction.

[NOTE]
=====
For more information, refer to the *`LoongArch Architecture manual:2.2.5.4` / `2.2.5.5`* .
=====
