===== *8.1.1.1 Arithmetic Operation Instructions*

====== *8.1.1.1.1 `ADD.{W/D}`, `SUB.{W/D}`*

*Syntax:*

 opcode    dest,  src1,  src2

[options="header"]
[cols="70,10,10,10"]
|===========================
^.^|opcode
^.^|dest 
^.^|src1
^.^|src2

^.^|*`add.w`*, *`sub.w`*, *`add.d`*, *`sub.d`*
^.^|*`$rd`*
^.^|*`$rj`* 
^.^|*`$rk`*
|===========================

*Description :*

*`add.w`* : *`$rd`*[63:0] = *SignExtend*(*`$rj`*[31:0] *+* *`$rk`*[31:0], GRLEN)

*`sub.w`* : *`$rd`*[63:0] = *SignExtend*(*`$rj`*[31:0] *-* *`$rk`*[31:0], GRLEN)

*`add.d`* : *`$rd`*[63:0] = *`$rj`*[63:0] *+* *`$rk`*[63:0]

*`sub.d`* : *`$rd`*[63:0] = *`$rj`*[63:0] *-* *`$rk`*[63:0]

*Usage :* 

[source]
----
add.w    $r23,  $r24,  $r25        # $r23 = $r24 + $r25   
sub.d    $r23,  $r24,  $r25        # $r23 = $r24 - $r25 
----

[NOTE]
=====
For more information, refer to the *`LoongArch instruction manual:2.2.1.1`* .
=====

====== *8.1.1.1.2 `ADDI.{W/D}`, `ADDU16I.D`*

*Syntax:*

 opcode    dest,  src1,  src2

[options="header"]
[cols="70,10,10,10"]
|===========================
^.^|opcode
^.^|dest 
^.^|src1
^.^|src2

^.^|*`addi.w`*, *`addi.d`*
^.^|*`$rd`*
^.^|*`$rj`* 
^.^|*`si12`*

^.^|*`addu16i.d`*
^.^|*`$rd`*
^.^|*`$rj`* 
^.^|*`si16`*
|===========================

*Description :*

*`addi.w`*    : *`$rd`*[63:0] = *SignExtend*( *`$rj`*[31:0] *+* *SignExtend*(*`si12`*, 32), GRLEN)

*`addi.d`*    : *`$rd`*[63:0] = *`$rj`*[63:0] *+* *SignExtend*(*`si12`*, 64)

* *`si12`* : 12 bit immediate, Signed value range(*`integer`*) : [*`-2048`, `2047`*] or [*`-0x800`, `0x7ff`*]

*`addu16i.d`* : *`$rd`*[63:0] = *`$rj`*[63:0] *+* *SignExtend*({*`si16`*, 16'b0}, 64)

* *`si16`* : 16 bit immediate, Signed value range(*`integer`*) : [*`-32768`, `32767`*] or [*`-0x8000`, `0x7fff`*]

** The input *`si16`* is the value *`before`* the *`offset operation`*.

*Usage :* 

[source]
----
li.w             $r24, 1024               # $24 = 1024
addi.w           $r23, $r24, 1024         # $23 = 2048
addi.d           $r25, $r24, 2048         # $25 = 4096

li.d             $r26, 8                  # $26 = 8
addu16i.d        $r27, $r26, -32768       # $27 = -2147483640
----

* *Explanation :*

** The LA64 of *`-32768`* is *`0x8000`*, shifts the 16-bit immediate sil6 logic to the left by 16 bits, shifts the 16-bit immediate *`si16`* logic to the left by 16 bits, the result is *`0x80000000`* or *`-2147483648`* . Expand the range of immediate numbers.


[NOTE]
=====
For more information, refer to the *`LoongArch instruction manual:2.2.1.2`* .
=====

====== *8.1.1.1.3 `ALSL.{W[U]/D}`, `ALSL.D`*

*Syntax:*

 opcode    dest,  src1,  src2,  ShiftAmount

[options="header"]
[cols="50,10,10,10,20"]
|===========================
^.^|opcode
^.^|dest 
^.^|src1
^.^|src2
^.^|ShiftAmount

^.^|*`alsl.w`*, *`alsl.wu`*
^.^|*`$rd`*
^.^|*`$rj`* 
^.^|*`$rk`*
^.^|*`1`,`2`,`3`,`4`*

^.^|*`alsl.d`*
^.^|*`$rd`*
^.^|*`$rj`* 
^.^|*`$rk`*
^.^|*`1`,`2`,`3`,`4`*
|===========================

*Description :*

*`alsl.w`* : *`$rd`*[63:0] = *SignExtend*( ( (*`$rj`*[31:0]<<(*`ShiftAmount`*) ) *+* *`$rk`*[31:0] )[31:0], GRLEN)

*`alsl.wu`* : *`$rd`*[63:0] = *ZeroExtend*( ( (*`$rj`*[31:0]<<(*`ShiftAmount`*) ) *+* *`$rk`*[31:0] )[31:0], GRLEN)

*`alsl.d`* : *`$rd`*[63:0] =  ( (*`$rj`*[63:0]<<(*`ShiftAmount`*) ) *+* *`$rk`*[63:0] )

*Usage :*
[source]
----
li.w     $r24, 8                   # $r24 = 8
li.w     $r25, 4                   # $r25 = 4
alsl.w   $r23, $r24, $r25, 2       # $r23 = 8<<2 + 4 = 36         
----

[NOTE]
=====
For more information, refer to the *`LoongArch instruction manual:2.2.1.3`* .
=====

====== *8.1.1.1.4 `LU12I.W`, `LU32I.D`, `LU52I.D`*

*Syntax:*

 opcode    dest,  src1,  {src2}

[options="header"]
[cols="70,10,10,10"]
|===========================
^.^|opcode
^.^|dest 
^.^|src1
^.^|src2

^.^|*`lu12i.w`*, *`lu32i.d`*
^.^|*`$rd`*
^.^|*`si20`* 
^.^|

^.^|*`lu52i.d`*
^.^|*`$rd`*
^.^|*`$rj`*
^.^|*`si12`*
|===========================

*Description :*

*`lu12i.w`* : *`$rd`*[63:0] = *SignExtend*({*`si20`*, 12'b0}, GRLEN)

*`lu32i.d`* : *`$rd`*[63:0] = {*SignExtend*(*`si20`*, 32), *`$rd`*[31:0]}

* *`si20`* : 20 bit immediate, Signed value range(*`integer`*) : [*`-524288`, `524287`*] or [*`-0x80000`, `0x7ffff`*]

*`lu52i.d`* : *`$rd`*[63:0]  = {*`si12`*, *`$rj`*[51:0]}

* *`si12`* : 12 bit immediate, Signed value range(*`integer`*) : [*`-2048`, `2047`*] or [*`-0x800`, `0x7ff`*]

*Usage :* 
[source]
----
lu12i.w $r23, 0x76543          # $r23 = 0x0000000076543000
addi.d  $r23, $r23, 0x321      # $r23 = 0x0000000076543210
lu32i.d $r23, 0xcba98          # $r23 = 0x000cba9876543210 	        
lu52i.d $r23, $r23, 0xfed      # $r23 = 0xfedcba9876543210 	
----

* *Explanation :*

** The loading of immediate number in LoongArch is very cumbersome, and pseudo instructions are generally used when writing assembly files:

*** *`li.w`* *`$rd`*, *`imm32`*

*** *`li.d`* *`$rd`*, *`imm64`*

[NOTE]
=====
For more information, refer to the *`LoongArch instruction manual:2.2.1.4`* .
=====

====== *8.1.1.1.5 `SLT[U]`*

*Syntax:*

 opcode    dest,  src1,  src2

[options="header"]
[cols="70,10,10,10"]
|===========================
^.^|opcode
^.^|dest 
^.^|src1 
^.^|src2

^.^|*`slt`*, *`sltu`*
^.^|*`$rd`*
^.^|*`$rj`*
^.^|*`$rk`*
|===========================

*Description :*

*`slt`* : *`$rd`* = (signed(*`$rj`*) *<* signed(*`$rk`*)) ? 1 : 0

*`sltu`* : *`$rd`* = (unsigned(*`$rj`*) *<* unsigned(*`$rk`*)) ? 1 : 0

*Usage :* 
[source]
----
slt/sltu  $r23, $r24, $r25         
----

[NOTE]
=====
For more information, refer to the *`LoongArch instruction manual:2.2.1.5`* .
=====

====== *8.1.1.1.6 `SLT[U]I`*

*Syntax:*

 opcode    dest,  src1,  src2

[options="header"]
[cols="70,10,10,10"]
|===========================
^.^|opcode
^.^|dest 
^.^|src1 
^.^|src2

^.^|*`slti`*, *`sltui`*
^.^|*`$rd`*
^.^|*`$rj`*
^.^|*`si12`*
|===========================

*Description :*

*`slti`* : *`$rd`* = (signed(*`$rj`*) *<* signed(*SignExtend*(*`si12`*, GRLEN) ) ) ? 1 : 0

*`sltui`* : *`$rd`* = (unsigned(*`$rj`*) *<* unsigned(*SignExtend*(*`si12`*, GRLEN) ) ) ? 1 : 0

* *`si12`* : 12 bit immediate, Signed value range(*`integer`*) : [*`-2048`, `2047`*] or [*`-0x800`, `0x7ff`*]

*Usage :* 
[source]
----
slti/sltui  $r23, $r24, 1            
----

[NOTE]
=====
For more information, refer to the *`LoongArch instruction manual:2.2.1.6`* .
=====

====== *8.1.1.1.7 `PCADDI`, `PCADDU12I`, `PCADDU18I`, `PCALAU12I`*

*Syntax:*

 opcode    dest,  src1

[options="header"]
[cols="80,10,10"]
|===========================
^.^|opcode
^.^|dest 
^.^|src1 

^.^|*`pcaddi`*, *`pcaddu12i`*, *`pcaddu18i`*, *`pcalau12i`*
^.^|*`$rd`*
^.^|*`si20`*
|===========================

*Description :*

*`pcaddi`* : *`$rd`*[63:0] = *PC* *+* *SignExtend*({*`si20`*, 2'b0}, GRLEN)

*`pcaddu12i`* : *`$rd`*[63:0] = *PC* *+* *SignExtend*({*`si20`*, 12'b0}, GRLEN)

*`pcaddu18i`* : *`$rd`*[63:0] = *PC* *+* *SignExtend*({*`si20`*, 18'b0}, GRLEN)

*`pcalau12i`* : *`$rd`*[63:0] = {(*PC* *+* *SignExtend*({*`si20`*, 12'b0}, GRLEN) )[GRLEN-1:12], 12'b0}

* *`si20`* : 20 bit immediate, Signed value range(*`integer`*) : [*`-524288`, `524287`*] or [*`-0x80000`, `0x7ffff`*]

** The input *`si20`* is the value *`before`* the *`offset operation`*.

*Usage :* 
[source]
----
pcaddi    $r24, 0xf    # PC = 120000ba0; $r24 = 120000bdc
pcaddu12i $r24, 0xf    # PC = 120000bb8; $r24 = 12000fbb8        
pcaddu18i $r24, 0xf    # PC = 120000bd0; $r24 = 1203c0bd0
pcalau12i $r24, 0xf    # PC = 120000be8; $r24 = 12000f000
----

* *Explanation :*
 
** The *`PC`* value saved in *`$r24`* has actually increased by *`0x3c`*

** The *`PC`* value saved in *`$r24`* has actually increased by *`0xf000`*

** The *`PC`* value saved in *`$r24`* has actually increased by *`0x3c0000`*

** The *`PC`* value saved in *`$r24`* has actually increased by *`0xe418`*, And store it in *`$r14`* after the low bit of 12 is 0.

[NOTE]
=====
For more information, refer to the *`LoongArch instruction manual:2.2.1.7`* .
=====

====== *8.1.1.1.8 `AND`, `OR`, `NOR`, `XOR`, `ANDN`, `ORN`*

*Syntax:*

 opcode    dest,  src1,  src2

[options="header"]
[cols="70,10,10,10"]
|===========================
^.^|opcode
^.^|dest 
^.^|src1 
^.^|src2

^.^|*`and`*, *`or`*, *`nor`*, *`xor`*, *`andn`*, *`orn`*
^.^|*`$rd`*
^.^|*`$rj`*
^.^|*`$rk`*
|===========================

*Description :*

*`and`*  : *`$rd`*[63:0] = *`$rj`*[63:0] *&* *`$rk`*[63:0]

*`or`*   : *`$rd`*[63:0] = *`$rj`*[63:0] *|* *`$rk`*[63:0]

*`nor`*  : *`$rd`*[63:0] = *~*(*`$rj`*[63:0] *|* *`$rk`*[63:0])

*`xor`*  : *`$rd`*[63:0] = *`$rj`*[63:0] *^* *`$rk`*[63:0]

*`andn`* : *`$rd`*[63:0] = *`$rj`*[63:0] *&* *~*(*`$rk`*[63:0])

*`orn`*  : *`$rd`*[63:0] = *`$rj`*[63:0] *|* *~*(*`$rk`*[63:0])

*Usage :* 
[source]
----    
li.d   $r24, 0x00000000ffad1235    # $r24 = 0x00000000ffad1235
li.d   $r25, 0x00000000ccdd2345    # $r25 = 0x00000000ccdd2345
and    $r23, $r24, $r25            # $r23 = 0x00000000cc8d0205
or     $r23, $r24, $r25            # $r23 = 0x00000000fffd3375
nor    $r23, $r24, $r25            # $r23 = 0xffffffff0002cc8a
xor    $r23, $r24, $r25            # $r23 = 0x0000000033703170
andn   $r23, $r24, $r25            # $r23 = 0x0000000033201030
orn    $r23, $r24, $r25            # $r23 = 0xffffffffffafdebf 
----

[NOTE]
=====
For more information, refer to the *`LoongArch instruction manual:2.2.1.8`* .
=====

====== *8.1.1.1.9 `ANDI`, `ORI`, `XORI`*

*Syntax:*

 opcode    dest,  src1,  src2

[options="header"]
[cols="70,10,10,10"]
|===========================
^.^|opcode
^.^|dest 
^.^|src1 
^.^|src2

^.^|*`andi`*, *`ori`*, *`xori`*
^.^|*`$rd`*
^.^|*`$rj`*
^.^|*`ui12`*
|===========================

*Description :*

*`andi`* : *`$rd`*[63:0] = *`$rj`*[63:0] *&* *ZeroExtend*(*`ui12`*, GRLEN)

*`ori`* : *`$rd`*[63:0] = *`$rj`*[63:0] *|* *ZeroExtend*(*`ui12`*, GRLEN)

*`xori`* : *`$rd`*[63:0] = *`$rj`*[63:0] *^* *ZeroExtend*(*`ui12`*, GRLEN)

* *`ui12`* : 12 bit immediate, Unsigned value range(*`integer`*) : [*`0`, `4095`*] or [*`0x000`, `0xfff`*]

*Usage :* 
[source]
----  
li.d   $r24, 0xffffffffffad1f0f    # $r24 = 0xffffffffffad1f0f  
andi   $r23, $r24, 0xff0           # $r23 = 0x0000000000000f00
ori    $r23, $r24, 0xff0           # $r23 = 0xffffffffffad1fff
xori   $r23, $r24, 0xff0           # $r23 = 0xffffffffffad10ff
----

[NOTE]
=====
For more information, refer to the *`LoongArch instruction manual:2.2.1.9`* .
=====

====== *8.1.1.1.10 `NOP`*

*Syntax:*

 nop

*Description :*

*`nop`* : *`andi`* *`$zero`*, *`$zero`*, 0

[NOTE]
=====
For more information, refer to the *`LoongArch instruction manual:2.2.1.10`* .
=====

====== *8.1.1.1.11 `MUL.{W/D}`, `MULH.{W[U]/D[U]}`,*

*Syntax:*

 opcode    dest,  src1,  src2

[options="header"]
[cols="70,10,10,10"]
|===========================

^.^|opcode
^.^|dest 
^.^|src1 
^.^|src2

^.^|*`mul.w`*, *`mul.d`*
^.^|*`$rd`*
^.^|*`$rj`*
^.^|*`$rk`*

^.^|*`mulh.w`*, *`mulh.d`*
^.^|*`$rd`*
^.^|*`$rj`*
^.^|*`$rk`*

^.^|*`mulh.wu`*, *`mulh.du`*
^.^|*`$rd`*
^.^|*`$rj`*
^.^|*`$rk`*

|===========================

*Description :*

*`mul.w`* : *`$rd`*[63:0] = *SignExtend*( (signed(*`$rj`*[31:0]) *×* signed(*`$rk`*[31:0]) )[31:0], GRLEN)

*`mul.d`* : *`$rd`*[63:0] = (signed(*`$rj`*[63:0]) *×* signed(*`$rk`*[63:0]) )[63:0]

*`mulh.w`* : *`$rd`*[63:0] = *SignExtend*( (signed(*`$rj`*[31:0]) *×* signed(*`$rk`*[31:0]) )[63:31], GRLEN)

*`mulh.d`* : *`$rd`*[63:0] = (signed(*`$rj`*[63:0]) *×* signed(*`$rk`*[63:0]) )[127:64]

*`mulh.wu`* : *`$rd`*[63:0] = *SignExtend*( (unsigned(*`$rj`*[31:0]) *×* unsigned(*`$rk`*[31:0]) )[63:32], GRLEN)

*`mulh.du`* : *`$rd`*[63:0] = (unsigned(*`$rj`*[63:0]) *×* unsigned(*`$rk`*[63:0]) )[127:64]

*Usage :* 

[source]
----    
li.d      $r26, 0x000000000000000f   # $r26 = 0x000000000000000f
li.d      $r27, 0xffffffff80000000   # $r27 = 0xffffffff80000000
mul.w     $r23, $r26, $r27           # $r23 = 0xffffffff80000000
mulh.w    $r24, $r26, $r27           # $r24 = 0xfffffffffffffff8
mulh.wu   $r25, $r26, $r27           # $r25 = 0x0000000000000007
li.d      $r26, 0x000000000000000f   # $r26 = 0x000000000000000f
li.d      $r27, 0x8000000000000000   # $r27 = 0x8000000000000000
mul.d     $r23, $r26, $r27           # $r23 = 0x8000000000000000
mulh.d    $r24, $r26, $r27           # $r24 = 0xfffffffffffffff8
mulh.du   $r25, $r26, $r27           # $r25 = 0x0000000000000007  
----

* *Explanation :*

** The signed operation result of *`$r26`* multiplied by *`$r27`* is *`0xfffff88000000`*, and the unsigned operation result is *`0x00000078000000`*. Because the operation results of *`$23`*, *`$24`*, and *`$25`* are all stored in registers after signed extend, only *`31 bit`* to *`0 bit`* are taken when viewing the operation results.

[NOTE]
=====
For more information, refer to the *`LoongArch instruction manual:2.2.1.11`* .
=====

====== *8.1.1.1.12 `MULW.D.W[U]`*

*Syntax:*

 opcode    dest,  src1,  src2

[options="header"]
[cols="70,10,10,10"]
|===========================

^.^|opcode
^.^|dest 
^.^|src1 
^.^|src2

^.^|*`mulw.d.w`*
^.^|*`$rd`*
^.^|*`$rj`*
^.^|*`$rk`*

^.^|*`mulw.d.wu`*
^.^|*`$rd`*
^.^|*`$rj`*
^.^|*`$rk`*

|===========================

*Description :*

*`mulw.d.w`* : *`$rd`*[63:0] = (signed(*`$rj`*[31:0]) *×* signed(*`$rk`*[31:0]) )[63:0]

*`mulw.d.wu`* : *`$rd`*[63:0] = (unsigned(*`$rj`*[31:0]) *×* unsigned(*`$rk`*[31:0]) )[63:0]

*Usage :* 
[source]
----    
li.d         $r26, 0x000000000000000f    # $r26 = 0x000000000000000f
li.d         $r27, 0xffffffff80000000    # $r27 = 0xffffffff80000000
mulw.d.w     $r23, $r26, $r27            # $r23 = 0xfffffff880000000
mulw.d.wu    $r24, $r26, $r27            # $r24 = 0x0000000780000000
----

[NOTE]
=====
For more information, refer to the *`LoongArch instruction manual:2.2.1.12`* .
=====

====== *8.1.1.1.13 `DIV.{W[U]/D[U]}`, `MOD.{W[U]/D[U]}`*

*Syntax:*

 opcode    dest,  src1,  src2

[options="header"]
[cols="70,10,10,10"]
|===========================

^.^|opcode
^.^|dest 
^.^|src1 
^.^|src2

^.^|*`mod.w`*, *`mod.d`*
^.^|*`$rd`*
^.^|*`$rj`*
^.^|*`$rk`*

^.^|*`mod.wu`*, *`mod.du`*
^.^|*`$rd`*
^.^|*`$rj`*
^.^|*`$rk`*

^.^|*`div.w`*, *`div.d`*
^.^|*`$rd`*
^.^|*`$rj`*
^.^|*`$rk`*

^.^|*`div.wu`*, *`div.du`*
^.^|*`$rd`*
^.^|*`$rj`*
^.^|*`$rk`*

|===========================

*Description :*

*`mod.w`* : *`$rd`*[63:0] = *SignExtend*( (signed(*`$rj`*[31:0]) *%* signed(*`$rk`*[31:0]) )[31:0], GRLEN)

*`mod.d`* : *`$rd`*[63:0] = signed(*`$rj`*[63:0]) *%* signed(*`$rk`*[63:0])

*`mod.wu`* : *`$rd`*[63:0] = *SignExtend*( (unsigned(*`$rj`*[31:0]) *%* unsigned(*`$rk`*[31:0]) )[31:0], GRLEN)

*`mod.du`* : *`$rd`*[63:0] = unsigned(*`$rj`*[63:0]) *%* unsigned(*`$rk`*[63:0])

*`div.w`* : *`$rd`*[63:0] = *SignExtend*( (signed(*`$rj`*[31:0]) */* signed(*`$rk`*[31:0]) )[31:0], GRLEN)

*`div.d`* : *`$rd`*[63:0] = signed(*`$rj`*[63:0]) */* signed(*`$rk`*[63:0])

*`div.wu`* : *`$rd`*[63:0] = *SignExtend*( (unsigned(*`$rj`*[31:0]) */* unsigned(*`$rk`*[31:0]) )[31:0], GRLEN)

*`div.du`* : *`$rd`*[63:0] = unsigned(*`$rj`*[63:0]) */* unsigned(*`$rk`*[63:0])

*Usage :* 
[source]
----    
li.d      $r26, 0x000000000000000f    # $r26 = 0x000000000000000f
li.d      $r27, 0xffffffff80000000    # $r27 = 0xffffffff80000000
div.w     $r23, $r26, $r27            # $r23 = 0xfffffffff7777778
div.wu    $r23, $r26, $r27            # $r23 = 0x0000000008888888
mod.w     $r23, $r26, $r27            # $r23 = 0xfffffffffffffff8
mod.wu    $r23, $r26, $r27            # $r23 = 0x0000000000000008    
li.d      $r26, 0x000000000000000f    # $r26 = 0x000000000000000f
li.d      $r27, 0x8000000000000000    # $r27 = 0x8000000000000000
div.d     $r23, $r26, $r27            # $r23 = 0xf777777777777778
div.du    $r23, $r26, $r27            # $r23 = 0x0888888888888888
mod.d     $r23, $r26, $r27            # $r23 = 0xfffffffffffffff8
mod.du    $r23, $r26, $r27            # $r23 = 0x0000000000000008   
----

[NOTE]
=====
For more information, refer to the *`LoongArch instruction manual:2.2.1.13`* .
=====
