===== *8.1.1.1 Arithmetic Operation Instructions*

====== *8.1.1.1.1 `ADD.{W/D}`, `SUB.{W/D}`*

*Syntax:*

 opcode    dest,  src1,  src2

[options="header"]
[cols="70,10,10,10"]
|===========================
^.^|opcode
^.^|dest 
^.^|src1
^.^|src2

^.^|*`add.w`*, *`sub.w`*, *`add.d`*, *`sub.d`*
^.^|*`$rd`*
^.^|*`$rj`* 
^.^|*`$rk`*
|===========================

*Description :*

[grid=none]
[frame=none]
[cols="65,20,915"]
|===========================
<.^|*`add.w`*
^.^|*:*
<.^|*`$rd`*[63:0] = `*Sign*`*Extend* (*`$rj`*[31:0] `*+*` *`$rk`*[31:0], GRLEN)

<.^|*`sub.w`*
^.^|*:*
<.^|*`$rd`*[63:0] = `*Sign*`*Extend* (*`$rj`*[31:0] `*-*` *`$rk`*[31:0], GRLEN)

<.^|*`add.d`*
^.^|*:*
<.^|*`$rd`*[63:0] = *`$rj`*[63:0] `*+*` *`$rk`*[63:0]

<.^|*`sub.d`*
^.^|*:*
<.^|*`$rd`*[63:0] = *`$rj`*[63:0] `*-*` *`$rk`*[63:0]
|===========================

*Usage :* 

[source]
----
add.w    $r23,  $r24,  $r25        # $r23 = $r24 + $r25   
sub.w    $r23,  $r24,  $r25        # $r23 = $r24 - $r25
add.d    $r23,  $r24,  $r25        # $r23 = $r24 + $r25   
sub.d    $r23,  $r24,  $r25        # $r23 = $r24 - $r25  
----

[NOTE]
=====
For more information, refer to the *`LoongArch Architecture manual:2.2.1.1`* .
=====

====== *8.1.1.1.2 `ADDI.{W/D}`, `ADDU16I.D`*

*Syntax:*

 opcode    dest,  src1,  src2

[options="header"]
[cols="70,10,10,10"]
|===========================
^.^|opcode
^.^|dest 
^.^|src1
^.^|src2

^.^|*`addi.w`*, *`addi.d`*
^.^|*`$rd`*
^.^|*`$rj`* 
^.^|*`si12`*

^.^|*`addu16i.d`*
^.^|*`$rd`*
^.^|*`$rj`* 
^.^|*`si16`*
|===========================

<<<

*Description :*

[grid=none]
[frame=none]
[cols="75,20,905"]
|===========================
<.^|*`addi.w`*
^.^|*:*
<.^|*`$rd`*[63:0] = `*Sign*`*Extend* (*`$rj`*[31:0] `*+*` `*Sign*`*Extend*(*`si12`*, 32), GRLEN)

<.^|*`addi.d`*
^.^|*:*
<.^|*`$rd`*[63:0] = *`$rj`*[63:0] `*+*` `*Sign*`*Extend* (*`si12`*, 64)
|===========================

* *`si12`* : 12-bit immediate, signed value range(*`integer`*) : [*`-2048`, `2047`*] or [*`-0x800`, `0x7ff`*]

[grid=none]
[frame=none]
[cols="105,20,875"]
|===========================
<.^|*`addu16i.d`*
^.^|*:*
<.^|*`$rd`*[63:0] = *`$rj`*[63:0] *`+`* `*Sign*`*Extend* ({*`si16`*, 16'b0}, 64)
|===========================

* *`si16`* : 16-bit immediate, signed value range(*`integer`*) : [*`-32768`, `32767`*] or [*`-0x8000`, `0x7fff`*]

** The input *`si16`* is the value *`before`* the *`offset operation`*.

*Usage :* 

[source]
----
li.w             $r24, 1024               # $24 = 1024
addi.w           $r23, $r24, 1024         # $23 = 2048
addi.d           $r25, $r23, 2048         # $25 = 4096
li.d             $r26, 8                  # $26 = 8
addu16i.d        $r27, $r26, -32768       # $27 = -2147483640
----

* *Explanation :*

** The LA64 of *`-32768`* is *`0x8000`*. Shifting the 16-bit immediate *`sil6`* logic to the left by 16 bits, as well as shifting the 16-bit immediate *`si16`* logic to the left by 16 bits, results in *`0x80000000`* or *`-2147483648`* . This expands the range of immediate numbers.


[NOTE]
=====
For more information, refer to the *`LoongArch Architecture manual:2.2.1.2`* .
=====

====== *8.1.1.1.3 `ALSL.{W[U]/D}`, `ALSL.D`*

*Syntax:*

 opcode    dest,  src1,  src2,  ShiftAmount

[options="header"]
[cols="50,10,10,10,20"]
|===========================
^.^|opcode
^.^|dest 
^.^|src1
^.^|src2
^.^|ShiftAmount

^.^|*`alsl.w`*, *`alsl.wu`*
^.^|*`$rd`*
^.^|*`$rj`* 
^.^|*`$rk`*
^.^|*`1`,`2`,`3`,`4`*

^.^|*`alsl.d`*
^.^|*`$rd`*
^.^|*`$rj`* 
^.^|*`$rk`*
^.^|*`1`,`2`,`3`,`4`*
|===========================

*Description :*

[grid=none]
[frame=none]
[cols="85,20,895"]
|===========================
<.^|*`alsl.w`*
^.^|*:*
<.^|*`$rd`*[63:0] = `*Sign*`*Extend* ( ( (*`$rj`*[31:0]<<(*`ShiftAmount`*) ) *`+`* *`$rk`*[31:0] )[31:0], GRLEN)

<.^|*`alsl.wu`*
^.^|*:*
<.^|*`$rd`*[63:0] = `*Zero*`*Extend* ( ( (*`$rj`*[31:0]<<(*`ShiftAmount`*) ) *`+`* *`$rk`*[31:0] )[31:0], GRLEN)

<.^|*`alsl.d`*
^.^|*:*
<.^|*`$rd`*[63:0] =  (*`$rj`*[63:0]<<(*`ShiftAmount`*) ) *`+`* *`$rk`*[63:0]
|===========================

*Usage :*
[source]
----
li.w     $r24, 8                   # $r24 = 8
----

[source]
----
li.w     $r25, 4                   # $r25 = 4
alsl.w   $r23, $r24, $r25, 2       # $r23 = (8<<2) + 4 = 36         
----

[NOTE]
=====
For more information, refer to the *`LoongArch Architecture manual:2.2.1.3`* .
=====

====== *8.1.1.1.4 `LU12I.W`, `LU32I.D`, `LU52I.D`*

*Syntax:*

 opcode    dest,  src1,  {src2}

[options="header"]
[cols="70,10,10,10"]
|===========================
^.^|opcode
^.^|dest 
^.^|src1
^.^|src2

^.^|*`lu12i.w`*, *`lu32i.d`*
^.^|*`$rd`*
^.^|*`si20`* 
^.^|

^.^|*`lu52i.d`*
^.^|*`$rd`*
^.^|*`$rj`*
^.^|*`si12`*
|===========================

*Description :*

[grid=none]
[frame=none]
[cols="85,20,895"]
|===========================
<.^|*`lu12i.w`*
^.^|*:*
<.^|*`$rd`*[63:0] = `*Sign*`*Extend* ({*`si20`*, 12'b0}, GRLEN)

<.^|*`lu32i.d`*
^.^|*:*
<.^|*`$rd`*[63:0] = {`*Sign*`*Extend* (*`si20`*, 32), *`$rd`*[31:0]}
|===========================

* *`si20`* : 20-bit immediate, signed value range(*`integer`*) : [*`-524288`, `524287`*] or [*`-0x80000`, `0x7ffff`*]

[grid=none]
[frame=none]
[cols="85,20,895"]
|===========================
<.^|*`lu52i.d`*
^.^|*:*
<.^|*`$rd`*[63:0]  = {*`si12`*, *`$rj`*[51:0]}
|===========================

* *`si12`* : 12-bit immediate, signed value range(*`integer`*) : [*`-2048`, `2047`*] or [*`-0x800`, `0x7ff`*]

*Usage :* 
[source]
----
lu12i.w   $r23, 0x76543          # $r23 = 0x0000000076543000
ori       $r23, $r23, 0x210      # $r23 = 0x0000000076543210
lu32i.d   $r23, 0xcba98          # $r23 = 0xfffcba9876543210 	        
lu52i.d   $r23, $r23, 0xfed      # $r23 = 0xfedcba9876543210 	
----

The loading of immediate number in *`LoongArch`* is very cumbersome, which is why pseudo-instructions are commonly used when writing assembly files:

[grid=none]
[frame=none]
[cols="150,20,830"]
|===========================
<.^|*`li.w $rd`*, *`si32`*
^.^|*:*
<.^|*`$rd`*[63:0]  = `*Sign*`*Extend* (*`si32`*, GRLEN)

<.^|*`li.d $rd`*, *`si64`*
^.^|*:*
<.^|*`$rd`*[63:0]  = *`si64`*
|===========================

*Usage :* 

[source]
----
li.d    $r23, 0xfedcba9876543210    # $r23 = 0xfedcba9876543210
li.d:
   lu12i.w   $r23, 0x76543          # $r23 = 0x0000000076543000
   ori       $r23, $r23, 0x210      # $r23 = 0x0000000076543210
   lu32i.d   $r23, 0xcba98          # $r23 = 0xfffcba9876543210 	        
   lu52i.d   $r23, $r23, 0xfed      # $r23 = 0xfedcba9876543210 	
----

[source]
----
li.w    $r23, 0x76543210            # $r23 = 0x0000000076543210
li.w:
   lu12i.w   $r23, 0x76543          # $r23 = 0x0000000076543000
   ori       $r23, $r23, 0x210      # $r23 = 0x0000000076543210
----

[NOTE]
=====
For more information, refer to the *`LoongArch Architecture manual:2.2.1.4`* .
=====

====== *8.1.1.1.5 `SLT[U]`*

*Syntax:*

 opcode    dest,  src1,  src2

[options="header"]
[cols="70,10,10,10"]
|===========================
^.^|opcode
^.^|dest 
^.^|src1 
^.^|src2

^.^|*`slt`*, *`sltu`*
^.^|*`$rd`*
^.^|*`$rj`*
^.^|*`$rk`*
|===========================

*Description :*

[grid=none]
[frame=none]
[cols="55,20,925"]
|===========================
<.^|*`slt`*
^.^|*:*
<.^|*`$rd`* = (*signed*(*`$rj`*) `*<*` *signed*(*`$rk`*)) ? `*1*` : `*0*`

<.^|*`sltu`*
^.^|*:*
<.^|*`$rd`* = (*unsigned*(*`$rj`*) `*<*` *unsigned*(*`$rk`*)) ? `*1*` : `*0*`
|===========================

*Usage :* 
[source]
----
li.d  $r24, 0xffffffffffffffff  # $r24 = 0xffffffffffffffff
li.d  $r25, 0x0000000000000001  # $r25 = 0x0000000000000001
slt   $r23, $r24, $r25          # $r23 = 1 
sltu  $r23, $r24, $r25          # $r23 = 0   
----

[NOTE]
=====
For more information, refer to the *`LoongArch Architecture manual:2.2.1.5`* .
=====

====== *8.1.1.1.6 `SLT[U]I`*

*Syntax:*

 opcode    dest,  src1,  src2

[options="header"]
[cols="70,10,10,10"]
|===========================
^.^|opcode
^.^|dest 
^.^|src1 
^.^|src2

^.^|*`slti`*, *`sltui`*
^.^|*`$rd`*
^.^|*`$rj`*
^.^|*`si12`*
|===========================

*Description :*

[grid=none]
[frame=none]
[cols="65,20,915"]
|===========================
<.^|*`slti`*
^.^|*:*
<.^|*`$rd`* = (*signed*(*`$rj`*) `*<*` *signed*(`*Sign*`*Extend*(*`si12`*, GRLEN) ) ) ? `*1*` : `*0*`

<.^|*`sltui`*
^.^|*:*
<.^|*`$rd`* = (*unsigned*(*`$rj`*) `*<*` *unsigned*(`*Sign*`*Extend*(*`si12`*, GRLEN) ) ) ? `*1*` : `*0*`
|===========================

* *`si12`* : 12-bit immediate, signed value range(*`integer`*) : [*`-2048`, `2047`*] or [*`-0x800`, `0x7ff`*]

*Usage :* 
[source]
----
li.d  $r24, 0xffffffffffffffff  # $r24 = 0xffffffffffffffff
slt   $r23, $r24, 1             # $r23 = 1 
sltu  $r23, $r24, 1             # $r23 = 0             
----

[NOTE]
=====
For more information, refer to the *`LoongArch Architecture manual:2.2.1.6`* .
=====

====== *8.1.1.1.7 `PCADDI`, `PCADDU12I`, `PCADDU18I`, `PCALAU12I`*

*Syntax:*

 opcode    dest,  src1

[options="header"]
[cols="80,10,10"]
|===========================
^.^|opcode
^.^|dest 
^.^|src1 

^.^|*`pcaddi`*, *`pcaddu12i`*, *`pcaddu18i`*, *`pcalau12i`*
^.^|*`$rd`*
^.^|*`si20`*
|===========================

*Description :*

[grid=none]
[frame=none]
[cols="105,20,875"]
|===========================
<.^|*`pcaddi`*
^.^|*:*
<.^|*`$rd`*[63:0] = *PC* `*+*` `*Sign*`*Extend* ({*`si20`*, 2'b0}, GRLEN)

<.^|*`pcaddu12i`*
^.^|*:*
<.^|*`$rd`*[63:0] = *PC* `*+*` `*Sign*`*Extend* ({*`si20`*, 12'b0}, GRLEN)

<.^|*`pcaddu18i`*
^.^|*:*
<.^|*`$rd`*[63:0] = *PC* `*+*` `*Sign*`*Extend* ({*`si20`*, 18'b0}, GRLEN)

<.^|*`pcalau12i`*
^.^|*:*
<.^|*`$rd`*[63:0] = {(*PC* `*+*` `*Sign*`*Extend* ({*`si20`*, 12'b0}, GRLEN) )[GRLEN-1:12], 12'b0}
|===========================

* *`si20`* : 20-bit immediate, signed value range(*`integer`*) : [*`-524288`, `524287`*] or [*`-0x80000`, `0x7ffff`*]

** The input *`si20`* is the value *`before`* the *`offset operation`*.

*Usage :* 
[source]
----
pcaddi    $r24, 0x0000f    # PC = 120000ba0; $r24 = 120000bdc
# PC   = 0x120000ba0, si20 = 0xf
# 0xf  = 0b00000000000000001111 -> 0b1111 -> 0b111100 -> 0x3c
# $r24 = 0x120000ba0 + 0x3c   = 0x120000bdc

pcaddu12i $r24, 0x0000f    # PC = 120000bb8; $r24 = 12000fbb8 
# PC   = 0x120000bb8, si20 = 0xf
# 0xf  = 0b00000000000000001111 -> 0b1111 -> 0b1111000000000000 -> 0xf000
# $r24 = 0x120000bb8 + 0xf000 = 0x12000fbb8
       
pcaddu18i $r24, 0x0000f    # PC = 120000bd0; $r24 = 1203c0bd0
# PC   = 0x120000bd0, si20 = 0xf
# 0xf  = 0b00000000000000001111 -> 0b1111 -> 0b1111000000000000000000 -> 0x3c0000
# $r24 = 0x120000bd0 + 0x3c0000 = 0x1203c0bd0

pcalau12i $r24, 0x0000f    # PC = 120000be8; $r24 = 12000f000
# PC   = 0x120000be8, si20 = 0xf
# 0xf  = 0b00000000000000001111 -> 0b1111 -> 0b1111000000000000 -> 0xf000
# temp = 0x120000be8 + 0xf000 = 0x12000fbe8
----

[source]
----
# $r24 = {temp[63:12], 12'b0} = 0x12000f000
# $r24 - PC = 0xe418 
----

* *Explanation :*
 
** The *`PC`* value saved in *`$r24`* has actually increased by *`0x3c`*

** The *`PC`* value saved in *`$r24`* has actually increased by *`0xf000`*

** The *`PC`* value saved in *`$r24`* has actually increased by *`0x3c0000`*

** The *`PC`* value saved in *`$r24`* has actually increased by *`0xe418`*

[NOTE]
=====
For more information, refer to the *`LoongArch Architecture manual:2.2.1.7`* .
=====

====== *8.1.1.1.8 `AND`, `OR`, `NOR`, `XOR`, `ANDN`, `ORN`*

*Syntax:*

 opcode    dest,  src1,  src2

[options="header"]
[cols="70,10,10,10"]
|===========================
^.^|opcode
^.^|dest 
^.^|src1 
^.^|src2

^.^|*`and`*, *`or`*, *`nor`*, *`xor`*, *`andn`*, *`orn`*
^.^|*`$rd`*
^.^|*`$rj`*
^.^|*`$rk`*
|===========================

*Description :*

[grid=none]
[frame=none]
[cols="55,20,925"]
|===========================
<.^|*`and`*
^.^|*:*
<.^|*`$rd`*[63:0] = (*`$rj`*[63:0]) `*&*` (*`$rk`*[63:0])

<.^|*`or`*
^.^|*:*
<.^|*`$rd`*[63:0] = (*`$rj`*[63:0]) `*\|*` (*`$rk`*[63:0])

<.^|*`xor`*
^.^|*:*
<.^|*`$rd`*[63:0] = (*`$rj`*[63:0]) `*^*` (*`$rk`*[63:0])

<.^|*`nor`*
^.^|*:*
<.^|*`$rd`*[63:0] = `*~*`( (*`$rj`*[63:0]) `*\|*` (*`$rk`*[63:0]) )

<.^|*`andn`*
^.^|*:*
<.^|*`$rd`*[63:0] = (*`$rj`*[63:0]) `*&*` (`*~*`(*`$rk`*[63:0]) )

<.^|*`orn`*
^.^|*:*
<.^|*`$rd`*[63:0] = (*`$rj`*[63:0]) `*\|*` (`*~*`(*`$rk`*[63:0]) )
|===========================

*Usage :* 
[source]
----    
li.d   $r24, 0x00000000ffad1235    # $r24 = 0x00000000ffad1235
li.d   $r25, 0x00000000ccdd2345    # $r25 = 0x00000000ccdd2345
and    $r23, $r24, $r25            # $r23 = 0x00000000cc8d0205
or     $r23, $r24, $r25            # $r23 = 0x00000000fffd3375
----

[NOTE]
=====
For more information, refer to the *`LoongArch Architecture manual:2.2.1.8`* .
=====

====== *8.1.1.1.9 `ANDI`, `ORI`, `XORI`*

*Syntax:*

 opcode    dest,  src1,  src2

[options="header"]
[cols="70,10,10,10"]
|===========================
^.^|opcode
^.^|dest 
^.^|src1 
^.^|src2

^.^|*`andi`*, *`ori`*, *`xori`*
^.^|*`$rd`*
^.^|*`$rj`*
^.^|*`ui12`*
|===========================

*Description :*

[grid=none]
[frame=none]
[cols="55,20,925"]
|===========================
<.^|*`andi`*
^.^|*:*
<.^|*`$rd`*[63:0] = (*`$rj`*[63:0]) `*&*` (`*Zero*`*Extend* (*`ui12`*, GRLEN))

<.^|*`ori`*
^.^|*:*
<.^|*`$rd`*[63:0] = (*`$rj`*[63:0]) `*\|*` (`*Zero*`*Extend* (*`ui12`*, GRLEN))

<.^|*`xori`*
^.^|*:*
<.^|*`$rd`*[63:0] = (*`$rj`*[63:0]) `*^*` (`*Zero*`*Extend* (*`ui12`*, GRLEN))
|===========================

* *`ui12`* : 12-bit immediate, unsigned value range(*`integer`*) : [*`0`, `4095`*] or [*`0x000`, `0xfff`*]

*Usage :* 
[source]
----  
li.d   $r24, 0xffffffffffad1f0f    # $r24 = 0xffffffffffad1f0f  
andi   $r23, $r24, 0xff0           # $r23 = 0x0000000000000f00
xori   $r23, $r24, 0xff0           # $r23 = 0xffffffffffad10ff
----

[NOTE]
=====
For more information, refer to the *`LoongArch Architecture manual:2.2.1.9`* .
=====

====== *8.1.1.1.10 `NOP`*

*Syntax:*

 nop

[NOTE]
=====
For more information, refer to the *`LoongArch Architecture manual:2.2.1.10`* .
=====

====== *8.1.1.1.11 `MUL.{W/D}`, `MULH.{W[U]/D[U]}`,*

*Syntax:*

 opcode    dest,  src1,  src2

[options="header"]
[cols="70,10,10,10"]
|===========================
^.^|opcode
^.^|dest 
^.^|src1 
^.^|src2

^.^|*`mul.w`*, *`mulh.w`*, *`mulh.wu`*
^.^|*`$rd`*
^.^|*`$rj`*
^.^|*`$rk`*

^.^|*`mul.d`*, *`mulh.d`*, *`mulh.du`*
^.^|*`$rd`*
^.^|*`$rj`*
^.^|*`$rk`*
|===========================

*Description :*

[grid=none]
[frame=none]
[cols="85,20,895"]
|===========================
<.^|*`mul.w`*
^.^|*:*
<.^|*`$rd`*[63:0] = `*Sign*`*Extend* ( (signed(*`$rj`*[31:0]) `*×*` signed(*`$rk`*[31:0]) )[31:0], GRLEN)

<.^|*`mulh.w`*
^.^|*:*
<.^|*`$rd`*[63:0] = `*Sign*`*Extend* ( (signed(*`$rj`*[31:0]) `*×*` signed(*`$rk`*[31:0]) )[63:32], GRLEN)

<.^|*`mulh.wu`*
^.^|*:*
<.^|*`$rd`*[63:0] = `*Sign*`*Extend* ( (unsigned(*`$rj`*[31:0]) `*×*` unsigned(*`$rk`*[31:0]) )[63:32], GRLEN)

<.^|*`mul.d`*
^.^|*:*
<.^|*`$rd`*[63:0] = (signed(*`$rj`*[63:0]) `*×*` signed(*`$rk`*[63:0]) )[63:0]

<.^|*`mulh.d`*
^.^|*:*
<.^|*`$rd`*[63:0] = (signed(*`$rj`*[63:0]) `*×*` signed(*`$rk`*[63:0]) )[127:64]

<.^|*`mulh.du`*
^.^|*:*
<.^|*`$rd`*[63:0] = (unsigned(*`$rj`*[63:0]) `*×*` unsigned(*`$rk`*[63:0]) )[127:64]
|===========================

*Usage :* 

[source]
----    
li.d      $r26, 0x000000000000000f   # $r26 = 0x000000000000000f
li.d      $r27, 0xffffffff80000000   # $r27 = 0xffffffff80000000

mul.w     $r23, $r26, $r27           # $r23 = 0xffffffff80000000
mulh.w    $r24, $r26, $r27           # $r24 = 0xfffffffffffffff8
mulh.wu   $r25, $r26, $r27           # $r25 = 0x0000000000000007

li.d      $r26, 0x000000000000000f   # $r26 = 0x000000000000000f
li.d      $r27, 0x8000000000000000   # $r27 = 0x8000000000000000

mul.d     $r23, $r26, $r27           # $r23 = 0x8000000000000000
mulh.d    $r24, $r26, $r27           # $r24 = 0xfffffffffffffff8
mulh.du   $r25, $r26, $r27           # $r25 = 0x0000000000000007  
----

* *Explanation :*

** The signed result of multiplying *`$r26`* by *`$r27`* is *`0xfffff88000000`*, while the unsigned result is *`0x00000078000000`*. Because the operation results of *`$23`*, *`$24`*, and *`$25`* are all stored in registers after signed extend, only bits *`31`* to *`0`* are taken when viewing the operation results.

[NOTE]
=====
For more information, refer to the *`LoongArch Architecture manual:2.2.1.11`* .
=====

====== *8.1.1.1.12 `MULW.D.W[U]`*

*Syntax:*

 opcode    dest,  src1,  src2

[options="header"]
[cols="70,10,10,10"]
|===========================
^.^|opcode
^.^|dest 
^.^|src1 
^.^|src2

^.^|*`mulw.d.w`*
^.^|*`$rd`*
^.^|*`$rj`*
^.^|*`$rk`*

^.^|*`mulw.d.wu`*
^.^|*`$rd`*
^.^|*`$rj`*
^.^|*`$rk`*
|===========================

*Description :*

[grid=none]
[frame=none]
[cols="105,20,875"]
|===========================
<.^|*`mulw.d.w`*
^.^|*:*
<.^|*`$rd`*[63:0] = (signed(*`$rj`*[31:0]) `*×*` signed(*`$rk`*[31:0]) )[63:0]

<.^|*`mulw.d.wu`*
^.^|*:*
<.^|*`$rd`*[63:0] = (unsigned(*`$rj`*[31:0]) `*×*` unsigned(*`$rk`*[31:0]) )[63:0]
|===========================

*Usage :* 
[source]
----    
li.d         $r26, 0x000000000000000f    # $r26 = 0x000000000000000f
li.d         $r27, 0xffffffff80000000    # $r27 = 0xffffffff80000000
mulw.d.w     $r23, $r26, $r27            # $r23 = 0xfffffff880000000
mulw.d.wu    $r24, $r26, $r27            # $r24 = 0x0000000780000000
----

[NOTE]
=====
For more information, refer to the *`LoongArch Architecture manual:2.2.1.12`* .
=====

====== *8.1.1.1.13 `DIV.{W[U]/D[U]}`, `MOD.{W[U]/D[U]}`*

*Syntax:*

 opcode    dest,  src1,  src2

[options="header"]
[cols="70,10,10,10"]
|===========================
^.^|opcode
^.^|dest 
^.^|src1 
^.^|src2

^.^|*`mod.w`*, *`div.w`*, *`mod.wu`*, *`div.wu`*
^.^|*`$rd`*
^.^|*`$rj`*
^.^|*`$rk`*

^.^|*`mod.d`*, *`div.d`*, *`mod.du`*, *`div.du`*
^.^|*`$rd`*
^.^|*`$rj`*
^.^|*`$rk`*
|===========================

*Description :*

[grid=none]
[frame=none]
[cols="75,20,905"]
|===========================
<.^|*`mod.w`*
^.^|*:*
<.^|*`$rd`*[63:0] = `*Sign*`*Extend* ( (signed(*`$rj`*[31:0]) `*%*` signed(*`$rk`*[31:0]) )[31:0], GRLEN)

<.^|*`div.w`*
^.^|*:*
<.^|*`$rd`*[63:0] = `*Sign*`*Extend* ( (signed(*`$rj`*[31:0]) `*÷*` signed(*`$rk`*[31:0]) )[31:0], GRLEN)

<.^|*`mod.wu`*
^.^|*:*
<.^|*`$rd`*[63:0] = `*Sign*`*Extend* ( (unsigned(*`$rj`*[31:0]) `*%*` unsigned(*`$rk`*[31:0]) )[31:0], GRLEN)

<.^|*`div.wu`*
^.^|*:*
<.^|*`$rd`*[63:0] = `*Sign*`*Extend* ( (unsigned(*`$rj`*[31:0]) `*÷*` unsigned(*`$rk`*[31:0]) )[31:0], GRLEN)

<.^|*`mod.d`*
^.^|*:*
<.^|*`$rd`*[63:0] = signed(*`$rj`*[63:0]) `*%*` signed(*`$rk`*[63:0])

<.^|*`div.d`*
^.^|*:*
<.^|*`$rd`*[63:0] = signed(*`$rj`*[63:0]) `*÷*` signed(*`$rk`*[63:0])

<.^|*`mod.du`*
^.^|*:*
<.^|*`$rd`*[63:0] = unsigned(*`$rj`*[63:0]) `*%*` unsigned(*`$rk`*[63:0])

<.^|*`div.du`*
^.^|*:*
<.^|*`$rd`*[63:0] = unsigned(*`$rj`*[63:0]) `*÷*` unsigned(*`$rk`*[63:0])
|===========================

*Usage :* 
[source]
----    
li.d      $r26, 0x000000000000000f    # $r26 = 0x000000000000000f
li.d      $r27, 0xffffffff80000000    # $r27 = 0xffffffff80000000

div.w     $r23, $r26, $r27            # $r23 = 0xfffffffff7777778
div.wu    $r23, $r26, $r27            # $r23 = 0x0000000008888888
mod.w     $r23, $r26, $r27            # $r23 = 0xfffffffffffffff8
mod.wu    $r23, $r26, $r27            # $r23 = 0x0000000000000008 
   
li.d      $r26, 0x000000000000000f    # $r26 = 0x000000000000000f
li.d      $r27, 0x8000000000000000    # $r27 = 0x8000000000000000

div.d     $r23, $r26, $r27            # $r23 = 0xf777777777777778
div.du    $r23, $r26, $r27            # $r23 = 0x0888888888888888
mod.d     $r23, $r26, $r27            # $r23 = 0xfffffffffffffff8
mod.du    $r23, $r26, $r27            # $r23 = 0x0000000000000008   
----

[NOTE]
=====
For more information, refer to the *`LoongArch Architecture manual:2.2.1.13`* .
=====
