===== *8.1.2.3 Floating-Point Conversion Instructions*

====== *8.1.2.3.1 `FCVT.S.D`, `FCVT.D.S`*

*Syntax:*

 opcode    dest,  src1

[options="header"]
[cols="80,10,10"]
|===========================
^.^|opcode
^.^|dest
^.^|src1

^.^|*`fcvt.s.d`*
^.^|*`$fd`*
^.^|*`$fj`* 

^.^|*`fcvt.d.s`*
^.^|*`$fd`*
^.^|*`$fj`* 
|===========================

*Description :*

[grid=none]
[frame=none]
[cols="100,20,880"]
|===========================
<.^|*`fcvt.s.d`*
^.^|*:*
<.^|*`$fd`*[31:0] = FP32 `*convertFormat*` (*`$fj`*[63:0], FP64)

<.^|*`fcvt.d.s`*
^.^|*:*
<.^|*`$fd`*[63:0] = FP64 `*convertFormat*` (*`$fj`*[31:0], FP32)
|===========================

* The floating-point *`format conversion`* operation follows the specification of the *`convertFormat`*(x) operation in the *`IEEE 754-2008 standard`* .

*Usage :* 
[source]
----
fcvt.s.d   $f23, $f27   # $f27 32 bit floating-point -> $f23 64 bit floating-point
fcvt.d.s   $f26, $f24   # $f24 64 bit floating-point -> $f26 32 bit floating-point
----

[NOTE]
=====
For more information, refer to the *`LoongArch Architecture manual:3.2.3.1`* .
=====

====== *8.1.2.3.2 `FFINT.{S/D}.{W/L}`, `FTINT.{W/L}.{S/D}`*

*Syntax:*

 opcode    dest,  src1

[options="header"]
[cols="80,10,10"]
|===========================
^.^|opcode
^.^|dest
^.^|src1

^.^|*`ffint.s.w`*, *`ffint.s.l`*, *`ffint.d.w`*, *`ffint.d.l`*
^.^|*`$fd`*
^.^|*`$fj`* 

^.^|*`ftint.w.s`*, *`ftint.w.d`*, *`ftint.l.s`*, *`ftint.l.d`*
^.^|*`$fd`*
^.^|*`$fj`* 
|===========================

*Description :*

[grid=none]
[frame=none]
[cols="105,20,875"]
|===========================
<.^|*`ffint.s.w`*
^.^|*:*
<.^|*`$fd`*[31:0] = FP32 `*convertFromInt*` ( *`$fj`*[31:0], SINT32 )

<.^|*`ffint.s.l`*
^.^|*:*
<.^|*`$fd`*[31:0] = FP32 `*convertFromInt*` ( *`$fj`*[63:0], SINT64 )

<.^|*`ffint.d.w`*
^.^|*:*
<.^|*`$fd`*[63:0] = FP64 `*convertFromInt*` ( *`$fj`*[31:0], SINT32 )

<.^|*`ffint.d.l`*
^.^|*:*
<.^|*`$fd`*[63:0] = FP64 `*convertFromInt*` ( *`$fj`*[63:0], SINT64 )
|===========================

* The *`FFINT{S/D}.{W/L}`* instruction selects the *`integer`*/*`long-integer`* fixed-point number from the floating-point register *`$fj`* and converts it into a *`single`*/*`double`* floating-point number. The resulting *`single`*/*`double`* floating-point number is then written to floating-point register *`$fd`*. The floating-point *`format conversion`* operation follows the specifications of the *`convertFromInt`*(x) operation in the *`IEEE 754-2008 standard`* .

[grid=none]
[frame=none]
[cols="105,20,875"]
|===========================
<.^|*`ftint.s.w`*
^.^|*:*
<.^|*`$fd`*[31:0] = FP32 `*convertTo*` Sint32 ( *`$fj`*[31:0], FCSR.RM )

<.^|*`ftint.s.l`*
^.^|*:*
<.^|*`$fd`*[63:0] = FP64 `*convertTo*` Sint32 ( *`$fj`*[63:0], FCSR.RM )

<.^|*`ftint.d.w`*
^.^|*:*
<.^|*`$fd`*[31:0] = FP32 `*convertTo*` Sint64 ( *`$fj`*[31:0], FCSR.RM )

<.^|*`ftint.d.l`*
^.^|*:*
<.^|*`$fd`*[63:0] = FP64 `*convertTo*` Sint64 ( *`$fj`*[63:0], FCSR.RM )
|===========================

* The *`FTINT{W/L}.{S/D}`* instruction selects the *`single`*/*`double`* floating-point number from the floating-point register *`$fj`* and converts it into an *`integer`*/*`long-integer`* fixed-point number. The resulting *`integer`*/*`long-integer`* fixed-point number is then written to the floating-point memory *`$fd`*. Depending on the different states in *`FCSR`*, the operations in the *`IEEE 754-2008 standard`* followed by this floating-point *`format conversion`* operation are shown in the following table.

---

*IEEE 754-2008 Standard* :

[options="header"]
[cols="5,6"]
|===========================
^.^|rounding mode
^.^|Operations in IEEE 754-2008 Standard

^.^|Round to the nearest even number
^.^|*`convertToIntegerExactTiesToEven`*(x)

^.^|Round to zero
^.^|*`convertToIntegerExactTowardZero`*(x)

^.^|Round towards positive infinity
^.^|*`convertToIntegerExactTowardPositive`*(x)

^.^|Round towards negative infinity
^.^|*`convertToIntegerExactTowardNegative`*(x)
|===========================

* *FP32convertToSint32* : 
[source]
----
 {bits(32) } FP32convertToSint32(bits(32) x, bits(2) rm):
  case {rm} of:
   {2'd0}: return Sint32_convertToIntegerExactTiesToEven(x)
   {2'd1}: return Sint32_convertToIntegerExactTowardZero(x)
   {2'd2}: return Sint32_convertToIntegerExactTowardPositive(x)
   {2'd3}: return Sint32_convertToIntegerExactTowardNegative(x)
----

* *FP64convertToSint32* : 
[source]
----
 {bits(64) } FP32convertToSint64(bits(32) x, bits(2) rm):
  case {rm} of:
   {2'd0}: return Sint32_convertToIntegerExactTiesToEven(x)
   {2'd1}: return Sint32_convertToIntegerExactTowardZero(x)
   {2'd2}: return Sint32_convertToIntegerExactTowardPositive(x)
   {2'd3}: return Sint32_convertToIntegerExactTowardNegative(x)
----

* *FP32convertToSint64* : 
[source]
----
 {bits(64) } FP64convertToSint32(bits(64) x, bits(2) rm):
  case {rm} of:
   {2'd0}: return Sint64_convertToIntegerExactTiesToEven(x)
   {2'd1}: return Sint64_convertToIntegerExactTowardZero(x)
----

[source]
----
   {2'd2}: return Sint64_convertToIntegerExactTowardPositive(x)
   {2'd3}: return Sint64_convertToIntegerExactTowardNegative(x)
----

* *FP64convertToSint64* : 
[source]
----
 {bits(64) } FP64convertToSint64(bits(64) x, bits(2) rm):
  case {rm} of:
   {2'd0}: return Sint64_convertToIntegerExactTiesToEven(x)
   {2'd1}: return Sint64_convertToIntegerExactTowardZero(x)
   {2'd2}: return Sint64_convertToIntegerExactTowardPositive(x)
   {2'd3}: return Sint64_convertToIntegerExactTowardNegative(x)
----

*Usage :* 
[source]
----
.LC282:
	.word	 1083179008        # 4.5
	.align	 3

la.local	 $r12, .LC282      # $r12 = &(.LC282)

fld.s	     $f24, $r12,  0    # $f24 = 4.5
ftint.w.s    $f25, $f24        # $f25 = 4 (0x4)
ffint.s.w    $f26, $f25        # $f26 = 4.0 
----

[NOTE]
=====
For more information, refer to the *`LoongArch Architecture manual:3.2.3.2`* .
=====

====== *8.1.2.3.3 `FTINT{RM/RP/RZ/RNE}.{W/L}.{S/D}`*

*Syntax:*

 opcode    dest,  src1

[options="header"]
[cols="80,10,10"]
|===========================
^.^|opcode
^.^|dest
^.^|src1

^.^|*`ftintrm.w.s`*, *`ftintrm.w.d`*, *`ftintrm.l.s`*, *`ftintrm.l.d`*
^.^|*`$fd`*
^.^|*`$fj`* 

^.^|*`ftintrp.w.s`*, *`ftintrp.w.d`*, *`ftintrp.l.s`*, *`ftintrp.l.d`*
^.^|*`$fd`*
^.^|*`$fj`* 

^.^|*`ftintrz.w.s`*, *`ftintrz.w.d`*, *`ftintrz.l.s`*, *`ftintrz.l.d`*
^.^|*`$fd`*
^.^|*`$fj`* 

^.^|*`ftintrne.w.s`*, *`ftintrne.w.d`*, *`ftintrne.l.s`*, *`ftintrne.l.d`*
^.^|*`$fd`*
^.^|*`$fj`* 
|===========================

*Description :*

[grid=none]
[frame=none]
[cols="130,20,850"]
|===========================
<.^|*`ftintrm.w.s`*
^.^|*:*
<.^|*`$fd`*[31:0] = Sint32 `*convertToIntegerExactTowardNegative*` (*`$fj`*[31:0])

<.^|*`ftintrm.w.d`*
^.^|*:*
<.^|*`$fd`*[31:0] = Sint32 `*convertToIntegerExactTowardNegative*` (*`$fj`*[63:0])

<.^|*`ftintrm.l.s`*
^.^|*:*
<.^|*`$fd`*[63:0] = Sint64 `*convertToIntegerExactTowardNegative*` (*`$fj`*[31:0])

<.^|*`ftintrm.l.d`*
^.^|*:*
<.^|*`$fd`*[63:0] = Sint64 `*convertToIntegerExactTowardNegative*` (*`$fj`*[63:0])
|===========================

* *`FTINTRM.{W/L}.{S/D}`* instruction selects the *`single`*/*`double`* floating-point number from the floating-point register *`$fj`* and converts it into *`integer`*/*`long-integer`* fixed point number. The resulting *`integer`*/*`long-integer`* fixed-point number is then written to the floating-point register *`$fd`*, using the "*`round to negative infinity`*" mode.

*Usage :* 
[source]
----
fld.s	     $f24, $r12,  0    # $f24 = 4.6
ftintrm.w.s  $f26, $f24        # $f26 = 4 (0x4)
fld.s	     $f24, $r12,  0    # $f24 = -4.6
ftintrm.w.s  $f26, $f24        # $f26 = -5 
fld.d	     $f24, $r12,  0    # $f24 = 4.6
ftintrm.l.d  $f26, $f24        # $f26 = 4 
fld.d	     $f25, $r12,  0    # $f25 = -4.6
ftintrm.l.d  $f26, $f25        # $f26 = -5 
----

*Description :*

[grid=none]
[frame=none]
[cols="130,20,850"]
|===========================
<.^|*`ftintrp.w.s`*
^.^|*:*
<.^|*`$fd`*[31:0] = Sint32 `*convertToIntegerExactTowardPositive*` (*`$fj`*[31:0])

<.^|*`ftintrp.w.d`*
^.^|*:*
<.^|*`$fd`*[31:0] = Sint32 `*convertToIntegerExactTowardPositive*` (*`$fj`*[63:0])

<.^|*`ftintrp.l.s`*
^.^|*:*
<.^|*`$fd`*[63:0] = Sint64 `*convertToIntegerExactTowardPositive*` (*`$fj`*[31:0])

<.^|*`ftintrp.l.d`*
^.^|*:*
<.^|*`$fd`*[63:0] = Sint64 `*convertToIntegerExactTowardPositive*` (*`$fj`*[63:0])
|===========================

* *`FTINTRP.{W/L}.{S/D}`* instruction selects the *`single`*/*`double`* floating-point number from the floating-point register *`$fj`* and converts it into *`integer`*/*`long-integer`* fixed-point number. It then writes the resulting *`integer`*/*`long-integer`* fixed-point number to the floating-point register *`$fd`*, using the "*`rounding to positive infinity`*" method.

*Usage :* 
[source]
----
fld.s	     $f24, $r12,  0    # $f24 = 4.6
ftintrp.w.s  $f26, $f24        # $f26 = 5 
fld.s	     $f25, $r12,  0    # $f25 = -4.6
ftintrp.w.s  $f26, $f25        # $f26 = -4 
fld.d	     $f25, $r12,  0    # $f25 = -4.6
ftintrp.l.d  $f26, $f25        # $f26 = -4 
fld.d	     $f25, $r12,  0    # $f25 = 4.6
ftintrp.l.d  $f26, $f25        # $f26 = 5 
----

*Description :*

[grid=none]
[frame=none]
[cols="130,20,850"]
|===========================
<.^|*`ftintrz.w.s`*
^.^|*:*
<.^|*`$fd`*[31:0] = Sint32 `*convertToIntegerExactTowardZero*` (*`$fj`*[31:0])

<.^|*`ftintrz.w.d`*
^.^|*:*
<.^|*`$fd`*[31:0] = Sint32 `*convertToIntegerExactTowardZero*` (*`$fj`*[63:0])

<.^|*`ftintrz.l.s`*
^.^|*:*
<.^|*`$fd`*[63:0] = Sint64 `*convertToIntegerExactTowardZero*` (*`$fj`*[31:0])

<.^|*`ftintrz.l.d`*
^.^|*:*
<.^|*`$fd`*[63:0] = Sint64 `*convertToIntegerExactTowardZero*` (*`$fj`*[63:0])
|===========================

* *`FTINTRZ.{W/L}.{S/D}`* instruction selects the *`single`*/*`double`* floating-point number from floating-point register *`$fj`* and converts it into *`integer`*/*`long-integer`* fixed-point number. It then writes the resulting *`integer`*/*`long-integer`* fixed-point number to the floating-point register *`$fd`*, using the "*`rounding to zero`*" method.

*Usage :* 
[source]
----
fld.s	     $f24, $r12,  0    # $f24 = 4.6
ftintrz.w.s  $f26, $f24        # $f26 = 4 
fld.s	     $f24, $r12,  0    # $f24 = -4.6
ftintrz.w.s  $f26, $f24        # $f26 = -4 
----

*Description :*

[grid=none]
[frame=none]
[cols="140,20,850"]
|===========================
<.^|*`ftintrne.w.s`*
^.^|*:*
<.^|*`$fd`*[31:0] = Sint32 `*convertToIntegerExactTiesToEven*` (*`$fj`*[31:0])

<.^|*`ftintrne.w.d`*
^.^|*:*
<.^|*`$fd`*[31:0] = Sint32 `*convertToIntegerExactTiesToEven*` (*`$fj`*[63:0])

<.^|*`ftintrne.l.s`*
^.^|*:*
<.^|*`$fd`*[63:0] = Sint64 `*convertToIntegerExactTiesToEven*` (*`$fj`*[31:0])

<.^|*`ftintrne.l.d`*
^.^|*:*
<.^|*`$fd`*[63:0] = Sint64 `*convertToIntegerExactTiesToEven*` (*`$fj`*[63:0])
|===========================

* *`FTINTRNE.{W/L}{S/D}`* instruction selects the *`single`*/*`double`* floating-point number from floating-point register *`$fj`* and converts it into *`integer`*/*`long-integer`* fixed-point number. It then writes the resulting *`integer`*/*`long-integer`* fixed-point number to floating-point register *`$fd`*, using the "*`rounding to the nearest even number`*" method.

*Usage :* 
[source]
----
fld.s	      $f24, $r12,  0    # $f24 = 4.6
ftintrne.w.s  $f26, $f24        # $f26 = 5 
fld.s	      $f24, $r12,  0    # $f24 = -4.6
ftintrne.w.s  $f26, $f24        # $f26 = -5 
fld.d	      $f25, $r12,  0    # $f25 = -4.4
ftintrne.l.d  $f26, $f25        # $f26 = -4 
fld.d	      $f25, $r12,  0    # $f25 = 4.4
ftintrne.l.d  $f26, $f25        # $f26 = 4 
----

[NOTE]
=====
For more information, refer to the *`LoongArch Architecture manual:3.2.3.3`* .
=====

====== *8.1.2.3.4 `FRINT.{S/D}`*

*Syntax:*

 opcode    dest,  src1

[options="header"]
[cols="80,10,10"]
|===========================
^.^|opcode
^.^|dest
^.^|src1

^.^|*`frint.s`*, *`frint.d`*
^.^|*`$fd`*
^.^|*`$fj`* 
|===========================

*Description :*

[grid=none]
[frame=none]
[cols="85,20,895"]
|===========================
<.^|*`frint.s`*
^.^|*:*
<.^|*`$fd`*[31:0] = FP32 `*roundToInteger*` (*`$fj`*[31:0])

<.^|*`frint.d`*
^.^|*:*
<.^|*`$fd`*[63:0] = FP64 `*roundToInteger*` (*`$fj`*[63:0])
|===========================

* The operations in *`IEEE 754-2008 standard`* for floating-point format
conversion are shown in the table below..

[options="header"]
[cols="5,6"]
|===========================
^.^|rounding mode
^.^|Operations in IEEE 754-2008 Standard

^.^|Round to the nearest even number
.4+^.^|*`roundToIntegralExact`*(x)

^.^|Round to zero

^.^|Round towards positive infinity

^.^|Round towards negative infinity
|===========================

* *FP32_roundToInteger* : 

 {bits(32) } FP32_roundToInteger(bits(N) x):
   return FP32_roundToIntegralExact(x)

* *FP64_roundToInteger* : 

 {bits(64) } FP64_roundToInteger(bits(N) x):
   return FP64_roundToIntegralExact(x)

*Usage :* 
[source]
----
fld.s	      $f24, $r12,  0    # $f24 = 4.5
frint.s       $f26, $f24        # $f26 = 4.0
fld.d	      $f24, $r12,  0    # $f24 = 4.6
frint.d       $f26, $f24        # $f26 = 5.0 
----

[NOTE]
=====
For more information, refer to the *`LoongArch Architecture manual:3.2.3.4`* .
=====
